### ISSUE TITLE
debugging/logging

### ISSUE THREAD

**Issue by demsey2** [tywalch/electrodb#106]
Is there any way to enable a debug mode or some kind of logging so I can see all the expressions sent to DynamoDB?

**Comment by tywalch** [comment]
Hey @demsey2, thank you for the question. I have considered including a “logger” property on the model to allow users to inject a logger for printing parameters, logging warnings and errors. Would that be something that could fit your needs?

**Comment by demsey2** [comment]
yes that would help a lot, not sure if that should be implemented on the model property or maybe on entity or service level

**Comment by tywalch** [comment]
I'll keep this thread updated with the status of this work 👍

I should mention (for something that could help in the short term), you can always use the ["params"](https://github.com/tywalch/electrodb#params) method to see the retrieve for a given query. This might not fit all scenarios, but can definitely help in one-off situations.

**Comment by tywalch** [comment]
@demsey2 checkout release 1.7.0 and let me know if you have any questions 👍

**Comment by demsey2** [comment]
that is perfect, thanks a lot
