### ISSUE TITLE
where clauses loses query typing

### ISSUE THREAD

**Issue by thdxr** [tywalch/electrodb#111]
In the following example:
```
  const result = await thing
    .update({
      id: input.id,
    })
    .data((attr, op) => {
    })
    .where((attr, op) => op.eq(attr.code, input.code))
    .go({
      response: "all_new",
    })
```

There is a type error on `response` because it loses the fact that it's an update query.  Removing the where clause fixes

**Comment by tywalch** [comment]
Great find, you can verify/check out the new typing [here](https://electrodb.fun/?#code/JYWwDg9gTgLgBAbzgUQHY2DAnnAvnAMyghDgCIBTAGwoGMZiATAIzIG4AoD2iVAZ3gwAFsFQBzOAF44qCgHcU6TFgAUHOInUa4ICI2oAuTdu0Ul2I2WGixZADRaTANwpQ+wXpYCM9x9r6uTsC0FJbW4gCGYGBkfrgOJhEwDMDMAK4wFHxGCH4awIw5edrYYKHkAlA2viYa8cU8+kW1JVhllqhpIMyuNbW4cQnaovoAHlnNtVB00IXGLXBgANaTC4TA1HNky31rPOAQ7plGANpkBWQAusV1Qy18K-NrBBtUWw+7C-uQR+Un12sBi0gdoQfUNEgYBFmDRLFgIGkoAB9KEwihI1AREAUMh4DgASk43F4AjgojAGSk8wKRgA5NDaLSho1yl4AEwAZg4Aw44TEWgAdGkwIwkhQVLkTDSyagKTABQUhrh8YLRVCVCokgw7HAIGB8VIAHyIZWCuRCVzizXJKA6vUGyTGvUCigAR2tDAFLJ15IyXr0FHxKo0ArEEAlcGmfEg-HKZAiVCoGPkuOVQA) and it is now available in `1.7.2` 👍 

I have another small typing-related release coming after this too, that will flatten many of the exposed types so they can be read easier in IDE. That will likely be `1.7.3`, so be on the look out for that as well.

Lastly, I have thought a bit more about about nested `default` map values and created an issue with more detail [here](https://github.com/tywalch/electrodb/issues/114).
