### ISSUE TITLE
Local Secondary Indexes

### ISSUE THREAD

**Issue by jpmtrabbold** [tywalch/electrodb#119]
Hey guys, great library! Any plans on supporting LSI's?

**Comment by tywalch** [comment]
Hey @jpmtrabbold! I assume the issue you ran into was the validation on key field names? I started a feature branch (https://github.com/tywalch/electrodb/pull/124) to help with this. I will need to add more tests but it is a pretty minor change to implement. Thank you for creating a ticket!

**Comment by jpmtrabbold** [comment]
@tywalch yeah, I didn’t find a way of doing LSI’s. Sounds good! Thanks for such a well thought off library!

**Comment by tywalch** [comment]
When this change is in, there won't be any difference in how you implement and map LSIs vs GSIs 👍

**Comment by jpmtrabbold** [comment]
@tywalch I updated to the latest version, but it seems like you didn't update the typescript definitions, so typescript is still complaining when I do a `new Entity(...)`.

Here's the `Schema` type that still requires a `pk`:

![image](https://user-images.githubusercontent.com/16899648/170403465-05d56451-6871-4494-a01e-e11bf97c7ac4.png)

**Comment by tywalch** [comment]
Hi @jpmtrabbold! Yes it's still necessary to map the PK in your model, the backing index type (LSI vs GSI) is opaque to ElectroDB so it only knows what is mapped in the model. In the case of your LSI, it would be the same PK definition as your table. 

Let me know if that helps, or if you have any cases where things don't update correctly; the PR has tests that check operations against an LSI.

**Comment by jpmtrabbold** [comment]
I see! Yeah man it worked a charm, thank you!
