### ISSUE TITLE
keys in lowercase

### ISSUE THREAD

**Issue by jpmtrabbold** [tywalch/electrodb#125]
hey guys. PK's and SK's content is being written in lowercase to dynamodb - can we have an option to disable that?

Here we have key templates like: 
`template: 'processId:${processId}:sourceProcessStepId:${sourceProcessStepId}',`

**Comment by tywalch** [comment]
Hey @jpmtrabbold yes, there is an option for casing on the model, more info here: https://github.com/tywalch/electrodb#index-casing

**Comment by jpmtrabbold** [comment]
wow - I must be very bad at searching, I swear I looked for it! Thanks man
