### ISSUE TITLE
Error in `parseModel` -> `normalize indexes`

### ISSUE THREAD

**Issue by calebwilson706** [tywalch/electrodb#126]
<img width="804" alt="Screenshot 2022-06-10 at 13 11 43" src="https://user-images.githubusercontent.com/71669491/173061711-e67d5bd1-98d0-42e8-b49b-f6a0642db185.png">

We are getting this error message when trying to put an item in to our database, from some debugging and logs we can see that when looping through the access patterns that there are extra access patterns after our defined ones which are return undefined for the index and hence throwing the issue above, some cloudwatch logs below show the extra "access patterns" 

<img width="782" alt="Screenshot 2022-06-10 at 13 11 02" src="https://user-images.githubusercontent.com/71669491/173062206-94264190-cd25-4501-8841-ab5cd7889e2c.png">

**Comment by tywalch** [comment]
Hi @calebwilson706

Thank you for reaching out! Does your model throw when using the [electrodb playground](https://electrodb.fun)? If so, would you be able to provide a playground like that demonstrates the issue? If not, would you be able to provide the version you are using, and a model that causes this exception?

**Comment by calebwilson706** [comment]
We are on version 1.8.4

**Comment by calebwilson706** [comment]
Our model is as follows (i have taken out any attribute which is not used for our indexes)
```
export const buildPartitionKey = (docmailMailingGuid: string): string => `${MAILING_PREFIX}${docmailMailingGuid}`;
export const buildSortKey = (): string => `${MAILING_PREFIX}`;
export const buildGsi1PartitionKey = (policyId: string): string => `${POLICY_PREFIX}${policyId}`;
export const buildGsi1SortKey = (effectiveDate: string): string => `${EFFECTIVE_DATE_PREFIX}${effectiveDate}`;
export const buildGsi2PartitionKey = (requestedAt: string): string => `${REQUESTED_AT_PREFIX}${requestedAt}`;
export const buildGsi2SortKey = (): string => `${REQUESTED_AT_PREFIX}`;

export const documentPrintRequest = new Entity(
  {
    model: {
      entity: "document print requests",
      version: "1",
      service: "docmail"
    },
    attributes: {
      partitionKey: {
        type: "string",
        required: true,
        readOnly: true
      },
      sortKey: {
        type: "string",
        required: true,
        readOnly: true,
        default: MAILING_PREFIX
      },
      gsi1PartitionKey: {
        type: "string",
        required: true,
        readOnly: true
      },
      gsi1SortKey: {
        type: "string",
        required: true,
        readOnly: true,
      },
      gsi2PartitionKey: {
        type: "string",
        required: true,
        readOnly: true
      },
      gsi2SortKey: {
        type: "string",
        required: true,
        readOnly: true,
        default: REQUESTED_AT_PREFIX
      },
      policyId: {
        type: "string",
        required: true
      },
      effectiveDate: {
        type: "string",
        required: true
      },
      docmailMailingGuid: {
        type: "string",
        required: true
      },
      requestedAt: {
        type: "string",
        required: true
      },
    },
    indexes: {
      byDocmailMailingGuid: {
        pk: {
          field: "partitionKey",
          composite: ["docmailMailingGuid"],
          casing: "none",
          template: buildPartitionKey("${docmailMailingGuid}")
        },
        sk: {
          field: "sortKey",
          composite: [],
          casing: "none",
          template: buildSortKey()
        }
      },
      byPolicyIdAndEffectiveDate: {
        index: "gsi1",
        pk: {
          field: "gsi1PartitionKey",
          composite: ["policyId"],
          template: buildGsi1PartitionKey("${policyId}"),
          casing: "none"
        },
        sk: {
          field: "gsi1SortKey",
          composite: ["effectiveDate"],
          template: buildGsi1SortKey("${effectiveDate}"),
          casing: "none"
        }
      },
      byRequestedAtDate: {
        index: "gsi2",
        pk: {
          field: "gsi2PartitionKey",
          composite: ["requestedAt"],
          template: buildGsi2PartitionKey("${requestedAt}"),
          casing: "none"
        },
        sk: {
          field: "gsi2SortKey",
          composite: [],
          template: buildGsi2SortKey(),
          casing: "none"
        }
      }
    }
  },
  {
    table: documentPrintRequestTableName,
    client: documentClient
  }
);```

**Comment by calebwilson706** [comment]
We have this defined in a shared folder and then we import it into our lambdas directory - would this make a difference

**Comment by tywalch** [comment]
@calebwilson706 I took the steps to reproduce, installing electrodb at the version you specified (`npm install electrodb@1.8.4`) and made a file with your model above, but was unable to  recreate the exception you shared. In looking at the error stack and its associated code, I would expect this to be throwing when your model is loaded. 

In the cloudwatch logs you shared it looks like the indexes are finding async functions for `forEachAsync`, `mapAsync`,  and `removeNull`, which suggest some of the values on the model might not be what is expected. I assume these logs are the result of printing the `i`, `accessPattern` and `index` values found at [this line](https://github.com/tywalch/electrodb/blob/master/src/entity.js#L2196)? 

I completely understand the need to sanitize models, though I think some of the dynamic implementation of the models might be at play here. The playground uses the same version as you have reported, so if you are able to recreate the issue there (even with "fake" attributes) that would be very helpful to help diagnose further.

----

Regarding the `ElectroValidationError` you posed, would you be able to share the attribute definition used for this attribute? Additionally, [here is a link](https://github.com/tywalch/electrodb/blob/master/src/schema.js#L9) to the code associated with identifying/validating the type of data received. 

I cannot speak for the type of data being passed (the value is not logged or captured in the error to avoid leaking private data) but it does seem to be working as designed: the value received was not of the expected type. For example, a `function` could be flagged as `unknown` given the above rules. 

The best course of action would be to add logging or further validation near the use of this put.

I'll leave this ticket open to maintain communication with you 👍

**Comment by calebwilson706** [comment]
i can update these 2 places if you would like, i'm not seeing any guide on contributing
