### ISSUE TITLE
Need a simple and accessible documentation site

### ISSUE THREAD

**Issue by anselm94** [tywalch/electrodb#141]
Hello 👋🏼! This is going to be more of a feature request. I tried `electrodb` for a pet project and really loved this library to achieve 'Single Table Design'. Thank you so much! 

However, as a new comer, though I could get started with `electrodb` without much hassle, I had trouble navigating the long [README](https://github.com/tywalch/electrodb/blob/master/README.md) page especially during reference lookup during implementation. A simple documentation site (eg - [Docusaurus](https://docusaurus.io/), [Vuepress](https://vuepress.vuejs.org/), [Mkdocs](https://www.mkdocs.org/) etc.) hosted in [GitHub Pages](https://pages.github.com/) would help onboard lot of new & experienced developers fairly quickly and easily. 

A quick high-level structure would look like

```
|- Docs
   |- Introduction - Project Goals
   |- Features
   |- Installation
   |- Key Concepts
   |- Typescript Support
   ...
|- Tutorials
   |- A basic tutorial (entities, attributes, queries, filters)
   |- Advanced tutorial (collections, services, joins)
|- Community
   |- GitHub Discussions
   |- Issues
   |- Contribution Guidelines
```

The `README` has lot of content in a single file. Having this broken down into multiple pages - accessible via a sidebar would greatly help! :)

**Comment by tywalch** [comment]
@anselm94 Thank you for taking the time to write out this feedback! I'd love to expand the documentation and see something just like this as well. I love the rough structure you laid out and over the next few months I hope to chip away at something like this 👍

**Comment by asquithea** [comment]
I found [Mkdocs Material](https://squidfunk.github.io/mkdocs-material/) to be powerful and very easy to work with.

In terms of examples, I can offer up [my own attempt at developer docs made for my previous company](https://atlas.mclarenapplied.com/integration/) (sadly already abandoned by the looks of it!)

I ended up including:
- an overview
- explanations of concepts
- tutorials walking through example code
- reference docs for each API feature
- an API reference

I can't speak to how useful my previous company's clients actually found this, though.

**Comment by anselm94** [comment]
Thank you @tywalch. This is already really helpful! 

I missed your previous comment. Thanks, @asquithea for filling in.
