### ISSUE TITLE
Issue with link to Playground

### ISSUE THREAD

**Issue by aisflat439** [tywalch/electrodb#143]
**Describe the bug**
The link does not work on line 1468 in the readme.

**Expected behavior**
The link works

**Errors**
```
404
```

**Additional context**
I'd fix this, but I'm not exactly sure what model you want to show this feature. Sorry :(

**Comment by tywalch** [comment]
[Fixed!](https://github.com/tywalch/electrodb/commit/9b8536fc813ab6c60972807d4c5cf5d7bedbb93e) Thank you so much!
