### ISSUE TITLE
Model Version is required, even though documentation says it's optional

### ISSUE THREAD

**Issue by samwiseduzer** [tywalch/electrodb#146]
My error: Runtime.UnhandledPromiseRejection: ElectroError: instance.model.version is required
The documentation: (optional) The version number of the schema, used to namespace keys

I very desperately do NOT want to namespace on model version and do not want to leverage this feature. However, I can't use this library without doing so.

I would deeply appreciate either:
- a docs update and a feature to disable automatic injection of model versions into keys
- or make model versions truly optional

Thanks for making this library- I'm very excited to actually get to use it!

**Comment by tywalch** [comment]
Hey Sam! I understand you're hoping to avoid using ElectroDB's versioning. Are you hoping to use Electro with an existing key schema or a new one (greenfield)? 

If you need the former, you can create your own keys with `template` and this will give you full control of your key structure. 

If the latter (a greenfield entity) then I would think simply setting the version value and never changing it would have the same effect as not including it at all. 

Is that correct?

**Comment by samwiseduzer** [comment]
Howdy! Thanks for the quick response!

It is greenfield, and I could definitely just never change the version. You might want to update the documentation to reflect that the version isn’t an optional attribute, however.

**Comment by tywalch** [comment]
Thank you for find that 👍

**Comment by tywalch** [comment]
Documentation has been updated
