### ISSUE TITLE
Required CustomAttribute not respected by TypeScript

### ISSUE THREAD

**Issue by aphex** [tywalch/electrodb#153]
**Describe the bug**
When using a required `customAttribute` it is still marked optional as far as TypeScript is concerned. However at runtime this will result in an Error.

**ElectroDB Version**
2.0.0

**ElectroDB Playground Link**
[(if possible) Use the [ElectroDB Playground](https://electrodb.fun) to recreate your issue and supply the link here to help with troubleshooting.](https://electrodb.fun/?#code/JYWwDg9gTgLgBAbzgUQHY2DAngGjgYygFMBDGIgYQFcBnGCEAQRhimACMry4BfOAMygM4AIiIAbIvlYQAJuxEBuAFDL8EVHTgwS7SXAC8orBCpQA+jr1FzqEiCJLV2METiNZIYKgBKEfUYIynDaWK4AXHAA5CSe3lHBcDRSxDCRdGyoAObKPM5hbgCqyVC+-m6BiS5EkTFxqAkh7CQ0wPjprN45ecrVcH4B7vUDbgA+cMVEpSOq6prwOjQA1jSGcKhEAO4o6JhYABSJQSEhIHISkccnIUS72JEiiysiOInXAG5TrRoPAIwvbxOJXebRqoieJDAYBEgJ4r2uZE6nHINEugJCwFkl1CEVEGS6Il48OucCEkkihFI5GodAYzCRXCIAB4RgA+fZXEmkogARyowGIWO0UCoRHRvAAlLDiRjULIiAAPIioxDisBsEAkKBYNFckJgJa6vUhfjACRCkQGgHGkLqcAQVrkSIAbREmJEAF1xSE4d6kobVTaBGbxBbltabXbII6wc6vca8lzfddE0SjtpdPo8hKVMoAPR5uAAFQKNEIwDACwAFt4Vtoa6tgKsIEs4MiUFAhFA4ABaHus3otFYAOkpZCIHMSmNqICwPcxCR4EuHWQg+ylyiAA)

**Entity/Service Definitions**
```
type AdminRole = {
  type: 'admin'
  secret: string
}

type UsernRole = {
  type: 'admin'
  basic: string
}

type Role = AdminRole | UsernRole

const tasks = new Entity(
  {
    model: {
      entity: "tasks",
      version: "1",
      service: "taskapp"
    },
    attributes: {
      id: { type: "string" },
      role: createCustomAttribute<Role>({
        required: true
      })
    },
    indexes: {
      primary: {
        pk: {
          field: "pk",
          composite: ["id"]
        },
        sk: {
          field: "sk",
          composite: []
        }
      },
    }
  },
  { table }
);
``` 

**Expected behavior**
Typescript should require role to be set to create/put 

**Errors**

**Additional context**

**Comment by tywalch** [comment]
I have found a good alternative approach for custom attributes and will be updating the library soon.
