### ISSUE TITLE
Attribute validation not invoked when using data update method

### ISSUE THREAD

**Issue by dangreaves** [tywalch/electrodb#162]
**Describe the bug**
When updating attributes via the `data()` update method, attribute validations are not invoked.

**ElectroDB Version**
`2.1.2`

**Entity/Service Definitions**

Using this entity, note that there is a `validate` method on the `prop1` attribute, which will fail if the attribute does not contain the substring `foo`.

```ts
{
    model: {
        entity: "my_entity",
        service: "my_service",
        version: "my_version"
    },
    attributes: {
        prop1: {
            type: "string",
            validate: (value) => !value.includes("foo"),
        },
        prop2: {
            type: "string"
        }
    },
    indexes: {
        record: {
            pk: {
                field: "pk",
                composite: ["prop1"],
            },
            sk: {
                field: "sk",
                composite: ["prop2"],
            },
        }
    } 
}
``` 

If we do this, then the validation fails as expected, and we get an error.

```ts
MyEntity.update({ entityID }).set({ prop1: "bar" });
```

However, if we do this instead, then the validation does not fail. In fact, the `validate` callback is not invoked at all.

```ts
MyEntity.update({ entityID }).data((attributes, operations) => {
  operations.set(attributes.prop1, "bar");
});
```

**Expected behavior**
Attribute validations should be invoked when using the update methods inside the `data` method.

**Additional context**
I understand that the underlying logic of the `data` method is probably different from the standard `set`, `update` etc, but the `data` method is really helpful for performing conditional operations. For example, I might call the `set` or `remove` operation based on the value of an attribute. This behavior is not possible using the default method chaining technique.

**Comment by tywalch** [comment]
Thank you! I will look into this this weekend!

**Comment by tywalch** [comment]
As a follow up, I'm hoping to get a change for this merged soon 👍
