### ISSUE TITLE
Get EntityType from Schema, not Entity

### ISSUE THREAD

**Issue by bestickley** [tywalch/electrodb#165]
With my current code I can get the `UserType` with `EntityItem<typeof users>`. My question is how can I get `UserType` from `userSchema`? My use case is I'd like to put `userSchema` and `UserType` into a common package so I can share the `UserType` between backend and frontend code. Thanks!

```ts
import { Entity, EntityItem, Schema } from "electrodb";

const userSchema: Schema<string, string, string> =  {
    model: {
      entity: "user",
      version: "1",
      service: "main",
    },
    attributes: {
      userId: {
        type: "string",
        readOnly: true,
        required: true,
      },
      email: {
        type: "string",
        required: true,
      },
      firstName: {
        type: "string",
        required: true,
      },
      lastName: {
        type: "string",
        required: true,
      },
      createdDate: {
        type: "string",
        default: () => new Date().toISOString(),
        readOnly: true,
      },
      updatedDate: {
        type: "string",
        readOnly: true,
        set: () => new Date().toISOString(),
        watch: "*",
      },
    },
    indexes: {
      primary: {
        pk: {
          field: "pk",
          composite: [],
        },
        sk: {
          field: "sk",
          composite: [],
        },
      },
    },
  };

const users = new Entity(userSchema, entityConfig);

type UserType = EntityItem<typeof users>;
```

**Comment by bestickley** [comment]
I tried `type UserType = ResponseItem<string, string, string, typeof userSchema>;` but that did not work.

**Comment by tywalch** [comment]
I'll see what I can shake out here. Note that the type defined by Electro expects the schema to be readonly so that its attribute and index properties don't get widened to be just "string" values. 

Just curious, could you go into your use-case for separating your schema definition? Knowing how folks use the library definitely impacts future development

**Comment by bestickley** [comment]
@tywalch, thanks! My use case is so I can share the UserType between backend and frontend code. I have a /common package where I'd like to export the interface of the UserType and I don't want to have to have the client or table defined in /common. Make sense?

**Comment by bestickley** [comment]
This issue is resolved with now having the ability to not specify entity configuration (second param) until after entity instantiation. See [here](https://electrodb.fun/?#code/PQKgBAsg9gJgpgGzARwK5wE4Es4GcA0YuccYGeqCALgUQBYCG5YA7llXWAGbZwB2MXGBDAAUKKwBbAA5QMVMAG8wAUT5V2AT0IBlTADcsAY1IBfbhiiSwAIkRwjVSzABGNgNzjxRqH1wKqBlwAazAAXjA+OBZVdS0ACkVRMDBJWEQALiVklLB+DSpNLJtAkJt8HJT9TFwsX2KARnLKogNjOGLS4IZpaRsc0wqUhionLBdUKjwspNywKYZJGZaUwukO239sPgBzZrmU8jQschgsp3QWwZau5YP5zXXiraxd-YOj1BO4M-mMS7m1zm0ksACsHFQ7gc1hsbC83kMPnBjqdzv84FdESlUMQMFC5jDnmMESsyMivqi-gDckDcgUEBtZtDHrD4XssblPt9fhc4BzaSl4LgjNhpBp6tl7oTNsS9piWv4Rjj8blgMAwDjSAw+GAmBgGJp5lAHutdTr+KhJKTpQBtGxQdZ8cq2V4AWhBUB25FwuGd9r4rroUAQMD9RgQUGIoYAurqhD4-FQOYK4FwGJRIbYHfx+oCObJXjQVasWcU+JaXJh3ikBfMGDtcMWTay4FRq7l2HBJI2Zds5YCBojXvAAB7TSW5D3gxw9pnA4JNlJcHAh4rSYLtuY+GSRztZO0LSQ2aOk2spEKL7gr35wjfJ1XqkVwEakbeyWpTMDBOCaIRcORgNITAaAwSC4HICjfoaaCYDguCkikb67lM+42FOEJ+l0x6nlcAyiKYACUnjiGqrQBAwLgMmAvh5HEGh4KIXQAHTEFQAAqFEMgAcoscDxAA5KxAD6vhCfkWj8UR4jMTBGCaEx6Ezokh5ZPxFFGPxhFMTsUDxFJogJv4rQYIYJjhJE0RgHoJntMpQTBIRJHqqxdaUaQNG4qZDGee0LGthxbk8ZIfGCa2Il8EJPkmJJxFRXATHifRuBMTJ6ByTkClghCuDKc+SxgGpLgaVpOl6e4QA) for example.

I'd still like to request a helper type to extract `EntityType` from schema object (with `as const`). I'll create another issue for that. Thanks, @tywalch!
