### ISSUE TITLE
Feature Request: Helper Type to Extract Entity Types from Schema object

### ISSUE THREAD

**Issue by bestickley** [tywalch/electrodb#167]
Given the following schema I'd like to have a helper types that's exported from `electrodb` that allows me to extract types so that I can use them in my frontend:
```ts
import { Putable, Getable, Schema, Updateable } from "electrodb";

const userSchema: Schema<string, string, string> =  {
    model: {
      entity: "user",
      version: "1",
      service: "main",
    },
    attributes: {
      userId: {
        type: "string",
        readOnly: true,
        required: true,
      },
      email: {
        type: "string",
        required: true,
      },
      firstName: {
        type: "string",
        required: true,
      },
      lastName: {
        type: "string",
        required: true,
      },
      createdDate: {
        type: "string",
        default: () => new Date().toISOString(),
        readOnly: true,
      },
      updatedDate: {
        type: "string",
        readOnly: true,
        set: () => new Date().toISOString(),
        watch: "*",
      },
    },
    indexes: {
      primary: {
        pk: {
          field: "pk",
          composite: [],
        },
        sk: {
          field: "sk",
          composite: [],
        },
      },
    },
  };

export type User = Getable<typeof userSchema>;
export type CreateUser = Putable<typeof userSchema>;
export type UpdateUser = Updateable<typeof userSchema>;
```

Requested types: `Getable`, `Putable`, `Updateable`.

Inspiration from [kysely](https://github.com/koskimas/kysely):
```ts
import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";
import type { ManagementRoleName } from "./management-role.js";
import type { ProductRoleName } from "./product-role.js";
import type { NullableColumn } from "./helper-types.js";

export interface UserTable {
  accessExpirationDate: string;
  adOid: string; // PK UUID
  altEmail: NullableColumn<string>;
  createdDate: ColumnType<string, never, never>;
  department: string;
  edipi: string;
  email: string;
  firstName: string;
  iaCompletionDate: string;
  jobTitle: string;
  lastName: string;
  middleInitial: NullableColumn<string>;
  organization: string;
  phone: string;
  updatedDate: ColumnType<string, never, never>;
}

export type User = Selectable<UserTable>;
export type CreateUser = Insertable<UserTable>;
export type UpdateUser = Updateable<UserTable>;
```

Earlier issue: #165

**Comment by RobbeCl** [comment]
There are already some helper types https://electrodb.dev/en/reference/typscript/#createentityitem-type and https://electrodb.dev/en/reference/typscript/#updateentityitem-type

**Comment by tywalch** [comment]
Hi @bestickley, `2.4.0` introduces `createSchema` which will allow you to create (and validate) a schema outside of Entity creation

**Comment by bestickley** [comment]
@tywalch, that's great news! Do you have any examples similar to my initial request above so that I can see how it works? I checked the docs [here](https://electrodb.dev/en/reference/typescript/) but couldn't find anything.

**Comment by tywalch** [comment]
Here is a playground! 

https://electrodb.fun/?#code/PQKgBAsg9gJgpgGzARwK5wE4Es4GcA0YuccYGeqCALgUQBYCG5YA7llXWAGbZwB2MXGBDAAUKKwBbAA5QMVMAG8wAUT5V2AT0IBjcgypwAyjrpxJDMAF9uGKJLAAiRHB1U7MAEaOA3OJ1QfLgKVAyeCKQAvE6aUKgYAPqh4XAJfAyScL7+gcFEpuaW0XpwBsYFFgAUiqJgYJKwiABcSrV1YPwaVJotjqG4ANaO+G11AG6YuFiBvQCMw6NEmGNYOnC9-QMM0tKObVYjdQbuWJ6ohrgtNe1ghhlXi3Xd0utOwdh8AOYLN3XkaFhyDAWu50IsDotNg9frdNC9eu8sF8fr9-qhAXBgbcMGCbhCbtI7AArVxUaG-Z6vRyI5GHVFwAFAkE4uDgul1VDEDDkm6UhEnWmPMgM9FM7G49r49pdCI86Vwqk077s9pojFY0FwFVSurwXB6LDSDQzVowvlvAXfNmLYIGTlyurAYBgTmkBh8MBMDAMTS3KCwl6ej38VCSIXmgDajigLz4wycSIAtISoJ9yLhcPHo3xE3QoAgYFmdAgoMRCwBdT1CAJBKgq3VwLgMShkpwx-h7PF0qVI+AADzwcpTJLcl1Nv2kAwd7S4OALvUnKJhARkpfYryjd0kjnLQp17UG07qs8QWOpQ3r7SdYBKZRv9lkU0MYAGcE0Qi4cjA0iYGgYSFwOQFFfX00EwHBcCFOoV0fdcWijYdSSzTYdz3cF9lEKwAEo-FEGs8k2MBoj4OAWFUdQtEqNp9TMCw6WUZIImsUQcPETYADowIwTR2MQ0dqi3FoAHIwh0ITsPYz4oEqHCgA

This will now actually be found in `2.4.1` because I made a foolish mistake. Let me know if you have any issues 👍

**Comment by bestickley** [comment]
Awesome, thanks @tywalch. 

Is it possible to have something like below?

```ts
/* Model queries, see results, share with friends */

import { Entity, createSchema, CreateEntityItem } from "electrodb";

const table = "your_table_name";

const schema = createSchema({
  model: {
    entity: "task",
    version: "1",
    service: "taskapp"
  },
  attributes: {
    team: {
      type: "string",
      required: true
    },
    task: {
      type: "string",
      required: true
    },
    project: {
      type: "string",
      required: true
    },
    user: {
      type: "string",
      required: true
    },
    title: {
      type: "string",
      required: true,
    },
    description: {
      type: "string"
    },
    status: {
      // use an array to type an enum
      type: ["open", "in-progress", "on-hold", "closed"] as const,
      default: "open"
    },
  },
  indexes: {
    projects: {
      pk: {
        field: "pk",
        composite: ["team"]
      },
      sk: {
        field: "sk",
        // create composite keys for partial sort key queries
        composite: ["project", "task"]
      }
    }
  }
});

// this errors out because it wants an entity. how can I create a `CreateEntityType` from schema?
type CreateEntityType = CreateEntityItem<typeof schema>;

const task = new Entity(
  schema,
  { table }
);

task.query.projects({team: 'abc'}).go();
```

**Comment by bestickley** [comment]
The docs say:
>The createSchema function allows you to define a schema independent of instantiating a new entity. This can be useful if the model definition needs to be portable or dynamic. This function will also validate your schema, and will throw if it is not a valid format.

I would think a portable model definition is only useful if you can get the interface or type of the entity from it. When I say entity, I don't mean electrodb's entity, but an entity like:
```ts
inteface User {
  id: string;
  firstName: string;
  lastName: string;
}
```

**Comment by bestickley** [comment]
I cannot create the `Entity` in my common package where I define my types because I don't know the table name there (only at run time). If I try I end up getting: https://electrodb.dev/en/reference/errors/#missing-table

**Comment by tywalch** [comment]
You can also add `table` to your execution options in `.go()`

```typescript
const results = await task.query
    .projects({team: 'abc'})
    .go({table: 'your_table_name'});
```

**Comment by bestickley** [comment]
I didn't know entity's have `.addTable` method! [This](https://electrodb.fun/?#code/PTAECMEMGMGsFoCmA7AJsAzgJ2sAtgPaqIA2GwALpBrAHQUYBQAlngA4FYWgDeoAosgrMKATwA0oaFkSQKiAMrQAFojyRJAYRlzEg4WICS8vKAC+oAGZYCpgESlE0CjdTg7AbkaNoBZBm4qcBJEUABeUDtRAgBXLAB9IJD45Eg8RE9vX39uDBU1SHCpHXklVXUACh5GUFBCYhIALl4a2tAUA1FmuyoaO3FW2oA3RCwMZj9ugEZ+wdAMUaHmaERu3thINjY7VrMB2rkXZnAY+Qxm6rbQeTSLudqxNlXIgKxmZABzWavamQBHGLMGSoZouGKIOZ7ObrO4-a6iJ7dV7vL77H7-QHA0FYcGQtG1Ng2ABWTgosJ+j2edmRn2+6MQAKBiBB1xxEKuUKuMQWWHJV0pSKOtPxbQxTJZYPZbU5bQMIT5soRVJpqPuoDFWNZ4JFMtqxDybzYwkmLThApeQq+eLmATk3IVtRAoG5oUgyFAkCwWEgomuBHhTw97pQMTwavNAG07AQnsh+pF3vBCQQPjIMBh49HkPBlAQSKhM9ASAQFgWALoejBSPwBEV6xCWSAxEhkyIxlA7DlomXvYgAD0Q51NbWTJOcQ8uPzYsAdbUszFILLs07pcN87BLImeUZueDsZbVuraNFntXni6RsFXPyd0lk8mrG-GD9giFEVcsnFAbE9wkgJHmThuFfX0AVGBcmDhWp1w4Z9t2XYlSUzdZ90PSFdkYMwAEovEYRA+w4Lhqxya5qFgIpkEQAB3AQhBEUQKlaPJykgRgcMYdZaAWCgABVIGCRAADk0kQCokkQLC8IIoCA1CbR70QPiaCKeTdH0ejjDUAAeSkCEsUiaAAPlwp0oDgJA0EwHBMEWZZB0oMj6CYJ1WEI7g+HWLQSkUsjzCsGx7FoWh8CIUhyE4hgdmoURkGgKwYli413TvXQlNgCp3jYU5mlU+Q0qw4dICoyARAMugUvkMSyMMZAsooLDaA+AgqlIgTzHYsxvCdaw-AoCz0GwXAAEEticvtGBcjciL4XKfOUiwevsPBRE2Nh4CozhYAwH8Vh2bIAjKmq6py7y0qKSdR1JbpLucOkYUiFC0V3NZZD3J6RHlB6PoyNEXV5SI-rpfVpGYI0JmQbpgcNJK6VtCh7TbWMdk6yxEAoFQKjsZQKAoNhzhAfC0jYEJaHXeM+HSChcyXAAFAB5BQePjcAiC6UAACkFDpwSuMtZhLAY9YjtOArsI8IA) is a working example of what I was looking for. Thank you!
