### ISSUE TITLE
Missing composite attributes error when using patch + delete

### ISSUE THREAD

**Issue by dangreaves** [tywalch/electrodb#182]
**Describe the bug**

When using the `patch` method in combination with the `delete` operation, ElectroDB throws the "Incomplete or invalid key composite attributes supplied" error, despite all index attributes being provided, and the same parameters working correctly when passed to the `update` method instead.

```js
// this works
tasks
  .update({ task, project, team })
  .remove(["description"])
  .params();

// this does not work
tasks
  .patch({ task, project, team })
  .remove(["description"])
  .params();
```

**ElectroDB Version**

```
2.3.2
```

**ElectroDB Playground Link**

https://codesandbox.io/p/sandbox/amazing-snowflake-3kt6bz?file=%2Findex.js

**Entity/Service Definitions**

I have added the ElectroDB playground model to the sandbox link above.

**Expected behavior**

It's expected that the `patch` method works the same as the `update` method, but with the implicit condition added to ensure that the document already exists.

**Errors**

```
ElectroError: Incomplete or invalid key composite attributes supplied. Missing properties: "team" - For more detail on this error reference: https://github.com/tywalch/electrodb#incomplete-composite-attributes
    at Entity._expectFacets (/project/sandbox/node_modules/electrodb/src/entity.js:2080:10)
    at Object.action (/project/sandbox/node_modules/electrodb/src/clauses.js:175:20)
    at Object.current.<computed> [as remove] (/project/sandbox/node_modules/electrodb/src/clauses.js:733:37)
    at file:///project/sandbox/index.js:141:4
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12) {
  _message: 'Incomplete or invalid key composite attributes supplied. Missing properties: "team"',
  ref: {
    code: 2002,
    section: 'incomplete-composite-attributes',
    name: 'IncompleteCompositeAttributes',
    sym: Symbol(error-code)
  },
  code: 2002,
  date: 1669637349858,
  isElectroError: true
}
```

**Additional context**

No additional context.

**Comment by tywalch** [comment]
I see the issue, this will be a quick fix, thank you 👍

**Comment by tywalch** [comment]
This is fix is in 👍

**Comment by dangreaves** [comment]
Confirmed that's working for me now. Thanks @tywalch 🎉
