### ISSUE TITLE
"Property x is missing in type" Typescript error when using setters to set properties that are in composite keys

### ISSUE THREAD

**Issue by brettneese** [tywalch/electrodb#184]
**Describe the bug**
Given this minimal [example gist](https://gist.github.com/brettneese/b1106e593485af68940b5ed515f6785b) that reproduces this error, I would expect that I should be able to create new items and autogenerate the `id` at the entity level. 

Instead, I get a Typescript error:

![image](https://user-images.githubusercontent.com/504279/204916503-f2bf7c0d-cd3d-466b-8fc7-f1ce0e225e70.png)

This makes sense -- the `id` is required in order to create an index and I do notCo encounter Typescript errors like this on attributes that are not part of the Composite Attributes. 

But it seems to make sense to me that I should be able to generate the `id` using an Attribute Setter, since downstream logic shouldn't concern itself with that. 

The workaround, of course, is to do something like the following:

```
 id: {
    type: "string",
    set: (id) => {
            if (!id) {
              return randomUUID();
            }
          },
          required: true,
          readOnly: true,
     }        
 ```

And then manually pass in an id when creating a new entity:

```
  const data = {
    name: "blah",
    id: randomUUID()
  };

  const item = await entity.create(data).go();
 ```
 
Or just not use an attribute setter for the `id` property. But that seems inelegant; I think ElectroDB Entities should be able to handle setting the `id` in a case like this, rather than relying on downstream logic. Since it's `readOnly`, I'm not worried about the warning in the readme about using attribute setters on Composite Attributes.

I'm not sure what the best solution, if any, is here, but happy to chip in if needed.

**ElectroDB Version**
2.3.3

**ElectroDB Playground Link**
[Example](https://electrodb.fun/?#code/PQKgBAsg9gJgpgGzARwK5wE4Es4GcA0YuccYGeqCALgUQBYCG5YA7llXWAGbZwB2MXGBDAAUKKwBbAA5QMVMAG8wAUT5V2AT0IBlTADcsAY1IBfbhiiSwAIkRwjVSzABGNgNwSZchcowMBKwBVIIBJABEwcx4rWyMMTWkqKA9xIyg+XAUqBhcEUgBeW00oVAwAfRy8uHK+Bkk4VNEwMHTMhX4NKk0wIr44FlV1LQAKZpalcYmwSVhEAC5J6enOrUWbeEMTG3wp5f1MXCwM9YBGHb3p4gwtuHXwuFu9G+NG3eWo9+WGKicsF1QVDwi0UlwmWBgILB0260jutiy2D4AHMLh8rnAqIsRgBKXoAPjIARgwTC4VxX3RZDgaCw5Eh3AYCGIlPR5AYMAA8nwEJpFk50KzpqYhRM6g0oVSWrD4TZEVgUWj0SKwSqPgr4AAPYFLdEQyVS6QAawNUu4OAQDJsxqVZvS3iOQMWAG0bBCbABdUXC72fVWstUTZRVfJRcY4zzNNpZMAwH4MXq6lri2V5Bh0JWmSOrboAOnicB+cBGcZyONzyKguM8QA)

**Entity/Service Definitions**
Include your entity model (or a model that sufficiently recreates your issue) to help troubleshoot.
```
    {
      model: {
        entity: "device",
        version: "1",
        service: "DeviceService",
      },
      attributes: {
        id: {
          type: "string",
          set: () => randomUUID(),
          required: true,
          readOnly: true
        },
        name: {
          type: "string",
        },
      },
      indexes: {
        id: {
          pk: {
            field: "pk",
            composite: ["id"],
          },
        },
      },
    }
``` 

**Expected behavior**
I expect to be able to delegate the setting of the `id` attribute to the ElectroDB entity, even though it's part of my primary key. 

**Errors**
```
error TS2345: Argument of type '{ name: string; }' is not assignable to parameter of type 'PutItem<string, string, string, { model: { entity: string; version: string; service: string; }; attributes: { id: { type: "string"; set: (id: string) => string; required: true; readOnly: true; }; name: { type: "string"; }; }; indexes: { ...; }; }>'.
  Property 'id' is missing in type '{ name: string; }' but required in type 'Pick<CreatedItem<string, string, string, { model: { entity: string; version: string; service: string; }; attributes: { id: { type: "string"; set: (id: string) => string; required: true; readOnly: true; }; name: { ...; }; }; indexes: { ...; }; }, { ...; }>, "id">'.
```

**Comment by tywalch** [comment]
Hi @brettneese 👋 

The `set` property is only called when the attribute is provided. You can use `default: () => randomUUID()` and omit a `set` all together to have your model automatically generate a UUID and to change the typing for `id` on  `create` / `put` / `upsert` to become optional. 

Here is an example in the playground: https://electrodb.fun/?#code/JYWwDg9gTgLgBAbzgUQHY2DAngGjgZQFMoA3YAY0LgF84AzKCEOAIkIBtDyZGATAIxYBuAFAjyEVAGd4MAIb9OcALyssEAK5QA+vMWFtqOSELCxE6fA0bgvFXAAUAShUA+OAHIQWbddsfRcUkZOEJ0TCx7VEIAdxRw7AcROERklLgQCF4OAC5U9PSwjGw8lmyyShYcNIKSYilgSVKARiqa9KliCsJSgBFCbqJSClNqguox9LkYHmB+DRhCKTyEdpTbFbX07DAe1hkoYFQAczaCgqhCAEcbS948ng1CSfO4S7leAHlUdiwHqCeL3O2Tocg07BgeWcbjgfl4ziBKQmWyMJk2rxSOz2LAOR1OiJoQORBSO2QAHkt0ecNvkMWAANZUjH0YAce6sBlnZlwCTgCANRZ5ADaLFsLAAugSkQTielZbKkHolNQRE5AhYQrxpnJ7KsUqjsYo5AALNrUQJFCIAOnI70WDi18icVuOEGcQiAA

**Comment by brettneese** [comment]
Ah @tywalch - that makes sense. I thought I was doing something wrong. Marking this as closed for others to reference if they run into an issue like this in the future. I might be interested in helping add these kinds of examples to documentation / examples as well as I really enjoy this library but it was a bit tricky to learn the ropes. I'll be in touch about that soon! Thank you so much! <3
