### ISSUE TITLE
Model versioning use cases

### ISSUE THREAD

**Issue by demsey2** [tywalch/electrodb#188]
ElectroDB supports model versioning, however, I would like to find out what are the use cases for that. When I change the versions, all new data will be saved with the new version but I am not able to fetch data using the previous one. 

Could anyone provide their way of using model versioning?

**Comment by tywalch** [comment]
Yes, originally the plan was to build out functionality that would allow you to query across versions for migrations. That could still happen but I haven't prioritized determining an API. The version number is positioned in the sort key to allow you to provide a partial sort key to easily use sort key operations (`<`, `<=`,  `>`, `>=`, `between`) on `version`.

Until then, it is another opportunity for entity isolation, the hierarchy for an entity is `service` -> `collection` -> `entity` -> `version`

**Comment by tywalch** [comment]
I think this would make a better "discussion" than an issue. I'm going close this but feel free to open a discussion for this 👍
