### ISSUE TITLE
Filter by size of a list attribute

### ISSUE THREAD

**Issue by RaeesBhatti** [tywalch/electrodb#208]
**Describe the bug**
Filter the query by using something equivalent of `size(#attribute)` method in DynamoDB.

**ElectroDB Version**
`2.3.5`

**ElectroDB Playground Link**
[Link](https://electrodb.fun/?#code/PQKgBAsg9gJgpgGzARwK5wE4Es4GcA0YuccYGeqCALgUQBYCG5YA7llXWAGbZwB2MXGBDAAUKKwBbAA5QMVMAG8wAUT5V2AT0IBlTADcsAY1IBfbhiiSwAIkRwjVSzABGNgNzijUPrgVUGFwRSAF5bTShUDAB9AKC4aL4GSTgPcVAwABUGXABrITUNKk1hMW9ffwwGI1zMITC+OBZVdS0AClEwJU6usElYRAAubt7e-iLNYZsnatqMG3we0f06rB8pgEYFpd7iDEMTKZmazAZpaRsd00XRhionLBdUKjxhxR2uozu4AHM5SZGo16xWkcCmfmwfB+2yBvXIaCw5Bgwyc6A+YGu6J+yTgAElkYDYSCwbYIVgoTDYWQ4AikSiMGjYZjYbhUC5cEZsC46m90V1icMAOQILB+QU3Knw1CIuAE1FwCWw9hwSS4XlU4GaUFCyRncV8uE06V0sDyxVU6SWUHyHBqwkasAqhhYBAAQRgMHIuDtygFYEFZKh4uptNl9PQGPNGo4XroUAQMAACthDkpTVqSYK+KhJNyMMGpTK5QyzFGgcyqRXRlXepy4N8YK6qOqqX6bNnc5hKbD4FwGJRm2A2gBKMAhAB8YAAIt8AHR8KAsEdlrrAYBgL58BcKbl9WBYLg4GBgBhcF4YDfkBsGq8wADyfAQAPl6JrXVQ0hgDabLaJGamHZ5t2QJrqwdxGJwXByBujBQngppQCefAlHcDxPC8BosOBdBTCAwGjKBxAKEYUTkOoppSHgAQyKwdD8GAH5fi8MAGkRwwjmOk4zi886LsuN71vej7PiWr5XOa5LwAAHq89qfN8fwYAC7watIuRvNwOAJlMakLBuViyLgyrDAA2jYXwvIpmg2AAupGrHqWmh6IASNh5Hp3gyFARkvKZgrYik+KCnZpivuaoVdBWvqBMEGKiMOniiKBDAeie+mSCk6iEAEPyEAwAgMZ+3xgMqkgBkQARUKgQhsBwaXlDA7BrHwojHHMuCzmgmCaLOFm-P8bSKH1VlCilKzqFEcCCqYw49LOLB0eQbRtKVhBQNIo4TmA62zj8VBtDtRkAF5wCtLySLOrLspyjx1MOhAAAzDrNXS7VAI6eEAA)

**Entity/Service Definitions**
```js
{
  model: {
    entity: "tracker",
    version: "1",
    service: "trackerapp"
  },
  attributes: {
    category: {
      type: "string",
      required: true
    },
    gameId: {
      type: "string",
      required: true
    },
    subscribers: {
      type: 'list',
      required: true,
      items: {
        type: 'map',
        required: true,
        properties: {
          emailAddress: { type: 'string', required: true },
          thresholdPrice: { type: 'number', required: true },
        },
      },
    },
    createdAt: {
      type: "number",
      default: () => Date.now(),
      // cannot be modified after created
      readOnly: true
    },
    updatedAt: {
      type: "number",
      // watch for changes to any attribute
      watch: "*",
      // set current timestamp when updated
      set: () => Date.now(),
      readOnly: true
    }
  },
  indexes: {
    category: {
      pk: { field: "pk", composite: ["category"] },
      sk: { field: "sk", composite: ['gameId'] }
    },
  }
}
``` 

**Expected behavior**
Be able to filter based on the size of `subscribers` attribute/property. Something like this:
```js
trackers.query.category({category: 'adventure'})
  .where((item, op) => op.gt(op.size(item.subscribers), 0))
  .go();
```

**Errors**
```
op.size is not a function
```

**Additional context**

**Comment by tywalch** [comment]
Hi @RaeesBhatti 👋 

ElectroDB version `2.4.0` introduces a `size()` function within the `where` clause. To perform the operation you expect you can use the following syntax:

```
trackers.query.category({category: 'adventure'})
  .where(({ subscribers }, {size, escape}) => `
    ${size(subscribers)} > ${escape(2)}
  `)
  .go();
  ```
  
  I will also add that the `where` clause is quite literally forming the `FilterExpression`.  So you can always implement any functions and/or any other pattern without the use of specialized `op` functions. For example:
  
  ```
  trackers.query.category({category: 'adventure'})
  .where(({ subscribers }, {name, escape}) => `
    size(${name(subscribers)}) > ${escape(2)}
  `)
  .go();
  ```

**Comment by RaeesBhatti** [comment]
Ah I see. Thank you! I tried to write a custom where clause and `FilterExpression` but it would just get dropped in the final query. I see now that I need to use `name()` to make sure it wouldn't.
