### ISSUE TITLE
`.params()` doesn't work with TransactWriteItems and v3 SDK

### ISSUE THREAD

**Issue by furrycatherder** [tywalch/electrodb#211]
**Describe the bug**
Trying to use a list of `.params()` with `TransactWriteItemsCommand` results in the cryptic error
```
TypeError: Cannot read properties of undefined (reading '0')
```

After some investigation, this seems to be the cause:
https://github.com/aws/aws-sdk-js-v3/issues/3365#issuecomment-1062842053

`.params()` returns something like this:

```json
{
    "Delete": {
        "Key": {
            "pk": "$sites#siteid_01gk976gqx9cqq63htxj0pbyer",
            "sk": "$devices#device_1#deviceid_01gqnz2pjv3cx8kx242dkjsw13"
        },
        "TableName": "dev-table-ng",
        "ConditionExpression": "attribute_exists(#pk) AND attribute_exists(#sk)",
        "ExpressionAttributeNames": {
            "#pk": "pk",
            "#sk": "sk"
        }
    }
}
```

But if I understand correctly it should be something like this:

```json
{
    "Delete": {
        "Key": {
            "pk": {"S": "$sites#siteid_01gk976gqx9cqq63htxj0pbyer"},
            "sk": {"S": "$devices#device_1#deviceid_01gqnz2pjv3cx8kx242dkjsw13"}
        },
        "TableName": "dev-table-ng",
        "ConditionExpression": "attribute_exists(#pk) AND attribute_exists(#sk)",
        "ExpressionAttributeNames": {
            "#pk": "pk",
            "#sk": "sk"
        }
    }
}
```

**ElectroDB Version**
`1.11.1`

**Comment by tywalch** [comment]
Hi @furrycatherder, ElectroDB returns unmarshalled params (used by the DocumentClient); If you're not able to use the DocumentClient, you could use the [`marshall` function from the @aws-sdk/util-dynamodb module](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_util_dynamodb.html#marshall) to get the format in your second example. 

The goal with the library thus far has been to avoid loading it up with too many bloated aws dependencies, which for some users is a big deal when they're up against deployment restrictions. This could be an opportunity however new Entity/Service options for `marshall`/`unmarshal` functions be passed. If that interests you, let me know, I could probably add that pretty easily 👍

**Comment by furrycatherder** [comment]
Sure, that sounds good. We're committed to using the v3 SDK at this point.

**Comment by tywalch** [comment]
Hey @furrycatherder 👋 

Version `2.5.0` was just shipped with transaction support, you can check it out here (works with the v3 client): https://electrodb.dev/en/mutations/transact-write/

**Comment by tywalch** [comment]
If you have any issues, please let me know, I'll close this ticket for now but feel free to reopen it if I missed anything
