### ISSUE TITLE
`create` with `SetAttribute` with no client results in `DynamoDBSet` being passed as param causing error

### ISSUE THREAD

**Issue by andrestone** [tywalch/electrodb#227]
**Describe the bug**
The issue is due to the fact that I'm not setting the client in the Entity (I do setClient afterwards).

Because SetAttribute is instantiated without access to a client, when checkCreate runs the getValidate on it, _createDDBSet returns a DynamoDBSet object instead of a Set or an Array:
```typescript
    _createDDBSet(value) {
        if (this.client && typeof this.client.createSet === "function") {
            value = Array.isArray(value)
                ? Array.from(new Set(value))
                : value;
            return this.client.createSet(value, { validate: true });
        } else {
            return new DynamoDBSet(value, this.items.type);
        }
    }
```

Maybe when setting the client using the setClient methods the Attributes instances should get their client set as well?
Out of curiosity, what's the use case for a DynamoDBSet? 

**ElectroDB Version**
2.5.1

**ElectroDB Playground Link**
**Entity/Service Definitions**
[See gist](https://gist.github.com/andrestone/278ef74b3f2775a4d13abc472f3ea0b2).

**Errors**
```
ElectroError: Error thrown by DynamoDB client: "Unsupported type passed: [object Object]. Pass options.convertClassInstanceToMap=true to marshall typeof object as map attribute." - For more detail on this error reference: https://electrodb.dev/en/reference/errors/#aws-error
```

**Comment by tywalch** [comment]
Hi @andrestone 👋 

Dang, this is a good find and I think your identification of the underlying issue is spot on! The good news is that I can create this issue very easily (thank you for taking the time to make a gist to help me do so), I will start to take a deeper look at this and hopefully have an update soon 👍

**Comment by Phrensoua** [comment]
@andrestone, @tywalch

hello, I am stuck with this issue. Is there any workarounds?

I have this attribute in my entity:
```
    tags: {
      type: 'set',
      items: 'string',
      required: true,
    },
```

and when I create the entity:
```
      // const q = this.entity.create(entity);
      const q = this.entity.create({
        ...
        tags: ['AAA', 'BBB'],
        ...
      });
      console.log('>-> Create Asset DDB:', q.params());
      return (await q.go({ logger: this.logger })).data;
```

I get this as console logs:
```
>-> Create Asset DDB: {
  Item: {
    ...
    tags: DynamoDBSet { wrapperName: 'Set', type: 'String', values: [Array] },
    ...
    createdAt: 1681326418618,
    updatedAt: 1681326418618,
    PK: '$xxxxxxx#id_01gxvdtansasahmtwywg79p941',
    SK: '$yyyyy_0.1',
    __edb_e__: 'yyyyy',
    __edb_v__: '0.1'
  },
  TableName: 'zzzzzzzzz',
  ConditionExpression: 'attribute_not_exists(#PK) AND attribute_not_exists(#SK)',
  ExpressionAttributeNames: { '#PK': 'PK', '#SK': 'SK' }
}
>-> AssetEntityItem CREATE ERROR: {
  "message": "Error thrown by DynamoDB client: \"Unsupported type passed: [object Object]. Pass options.convertClassInstanceToMap=true to marshall typeof object as map attribute.\" - For more detail on this error reference: https://electrodb.dev/en/reference/errors/#aws-error",
  "name": "ElectroError",
  "ref": {
    "code": 4001,
    "section": "aws-error",
    "name": "AWSError"
  },
  "code": 4001,
  "date": 1681326418618,
  "isElectroError": true
}
>-> asset create error: asset null.
```

Help! :)

Thank you!

**Comment by andrestone** [comment]
The easiest workaround is to set the client when constructing the entity.

```typescript
const myEntity = new Entity({...yourEntityProps},
  {
    client: yourDynamoDBClientInstance, // <-- This
    table: 'your-table',
  });
```

**Comment by Phrensoua** [comment]
@andrestone Thanks for the quick reply! But it looks like my issue is different, your fix is not fixing my problem.

**Comment by ekrata-main** [comment]
Sort of related: but given the attribute `tags: {
      type: 'set',
      items: 'string',
      default: [],
    }`

Removing the `default: []` stops this error from being thrown.

**Comment by tywalch** [comment]
This should be fixed in the latest version 👍
