### ISSUE TITLE
Incorrect type information when using data()

### ISSUE THREAD

**Issue by CaveSeal** [tywalch/electrodb#233]
Hello! Love the library!

**Describe the bug**
The issue occurs when you leave the `composite` field empty on the sort key for the base table. The first argument to the data() function when performing an update is missing the attributes of the entity in the resulting type.

**ElectroDB Version**
2.5.1

**ElectroDB Playground Link**
Oddly, it works in the [playground](https://electrodb.fun/?#code/PQKgBAsg9gJgpgGzARwK5wE4Es4GcA0YuccYGeqCALgUQBYCG5YA7llXWAGbZwB2MXGBDAAUKKwBbAA5QMVMAG8wAUT5V2ATzABfbhiiSwAIkRwAxlQMwARsYDc4uAA9Z8sOah9cC1MQxCALxgfHAsqupaABSKomBgkrCIAFxKcfFg-BpUmqnGfpjG+Onx-gBuWOZweWWYuFhenuoGCEUlYLUBDXx5AIzG6TrF8QxUVlg2qFR4qbEZYAUYfAyS1Wnz8TnSa8Y+2HwA5gPzQ+1clAgAcitrcxtbO3tYh8cZp-PSdFBUULPtm5ptnkni92u8MjYGn8NmAHsDxqCTsMMggoOZRt1ofdAY8EUcwcj4tJnqEYFj5nCTAw+JpXvFwfEuFAEKi2IdyRlKbs4FQ2jD2HBJLh4ft8UizszWXUOQCgSZiLzCRkBUKRc8xW8leZyKM4DAAIJUGWwnFql5K0o81JRACUYECAD4QmEwAARXW2gB0PwAkgBlADyfrxtotZDgDBgAb4CFysIw6CVDIW0hguoNRvWMJNct2eL52ZYo3MdDyIALMIV1rtjud4Xd0y9vsDwdFof+GR1UZjcasiYJg2Rz3gzhmWfii2NnhZFg0XjyUE6FTCFYy0gA1sb4p4ZFB6tNUgBtfL+ZarYwAXTDjJwCDJJg3dM1Hdwm-HGx3sn3a0PV47N8Qe9dnXJ96QHeYAH0p0lWdMRMKAWFJVd4mHFw8gOepeg3ABaDCsF6V9sNQ5xkLADctw8QwvwFI8T0wM84Eva9uFvIC8KwkCO2TUo3zuGEuFY9DMNfUjtyovcaLAX8uPAjJcFQGxcG1LBpDnbxoJnSw4OMIsqBLdVSOIoSsAAZhwvCTMI4jSPI995k-CSDykuilhuJj-xYwDjLMziYW4oheI8hzvyPP9s08u9vJEmSTkGUQdBtRxREWXBPVQVMPWURYGNSAByAArKA6D4XLdBtT00yoBgoiiSqGBrJ07jqz1ISgeKbVEIA) but not when I test the same code in my own environment.

I was able to reproduce the issue on [Codesandbox](https://codesandbox.io/s/elegant-sara-r50ztc?file=/src/index.ts).

**Entity/Service Definitions**
Include your entity model (or a model that sufficiently recreates your issue) to help troubleshoot.
```
import { Entity } from 'electrodb';
import moment from "moment";

export const users = new Entity({
  model: {
    entity: "user",
    service: "versioncontrol",
    version: "1"
  },
  attributes: {
    username: {
      type: "string"
    },
    fullName: {
      type: "string"
    },
    photo: {
      type: "string"
    },
    bio: {
      type: "string"
    },
    location: {
      type: "string"
    },
    pinned: {
      type: "any"
    },
    following: {
      type: "set",
      items: "string"
    },
    followers: {
      type: "set",
      items: "string"
    },
    createdAt: {
      type: "string",
      set: () => moment.utc().format(),
      readOnly: true,
    },
    updatedAt: {
        type: "string",
        watch: "*",
        set: () => moment.utc().format(),
        readOnly: true,
    },
  },
  indexes: {
    user: {
      collection: "overview",
      pk: {
        composite: ["username"],
        field: "pk"
      },
      sk: {
        composite: [],
        field: "sk"
      }
    },
    _: {
      collection: "owned",
      index: "gsi1pk-gsi1sk-index",
      pk: {
        composite: ["username"],
        field: "gsi1pk"
      },
      sk: {
        field: "gsi1sk",
        composite: []
      }
    },
    subscriptions: {
      collection: "watching",
      index: "gsi3pk-gsi3sk-index",
      pk: {
        composite: ["username"],
        field: "gsi3pk"
      },
      sk: {
        composite: [],
        field: "gsi3sk"
      }
    }
  }
});
``` 

**Expected behavior**
The type of data should have the attributes of the entity rather than an error message given by intellisense.

**Errors**

<img width="334" alt="Screenshot 2023-04-23 at 12 41 49" src="https://user-images.githubusercontent.com/52512664/233837681-55b8d423-37b1-4d9c-a024-a53327846d31.png">

```
Property 'username' does not exist on type 'W'. ts(2339)
```

**Comment by tywalch** [comment]
Hi @CaveSeal 👋

This is actually an easy one! The "username" property is a composite attribute in your primary. This makes that attribute read-only, since the pk and sk associated with the primary index in dynamodb are immutable. The typing knows this so username is absent in set because it cannot be changed.

**Comment by CaveSeal** [comment]
@tywalch Thanks for the quick response! In that case, my example was bad, because the same problem occurs for all attributes, like pinned or bio.

<img width="526" alt="Screenshot 2023-04-24 at 00 05 29" src="https://user-images.githubusercontent.com/52512664/233870921-90f18b73-4811-42d7-896f-9133f54d7284.png">

**Comment by tywalch** [comment]
I am not able to tell what version of TS that codesandbox uses, but I suspect that might be the issue here. Can you confirm which version you're currently using locally? There were some breaking changes in TS around the early/mid part of 4.* that might be the culprit here. Are you able to update to the latest version and verify what you're seeing against that? The playground uses the latest by default.

**Comment by CaveSeal** [comment]
I tried to set up a couple of projects to see if I could reproduce the issue I'm having, but it seemed to work just fine for all of them. It just doesn't work for one specific package in our monorepo and that CodeSandbox, both of which are on version `2.5.1`. The types in the `node_modules` are up to date, and I cross checked with a colleague too. It's all very strange.

Either way, it would seem this is a problem with something in my setup and not a problem on your end, so I will close the issue. Apologies for wasting your time.
