### ISSUE TITLE
Feature: Support format specifiers when using numbers in template for composite attributes

### ISSUE THREAD

**Issue by PaulJNewell77** [tywalch/electrodb#237]
This is a feature request to be able to specify how a number field is formatted (specifically, padding) when using it in a composite attribute. This is required in the case that a number field is used as (or part of) a string SK, to ensure that sorting is correct. For example, if you had a `dayOfMonth` field which is a number, to use as an SK it would need to be formatted by zero-padding to two characters: `01`, `02`, `03`, ...etc. This could be achieved by supporting format specifiers in the template such as `${dayOfMonth:2:0}`.

**Comment by tywalch** [comment]
Thanks for making these tickets, I am afk through next Monday but this one has a quick answer: there is an attribute property called "padding" that does this 👍

**Comment by PaulJNewell77** [comment]
Ah, I couldn't find it in the docs so didn't realise you'd implemented it since I spotted it originally. I'll give it a try, thanks.

**Comment by PaulJNewell77** [comment]
Hi, I've tried this feature (maybe not correctly ;)

My day attribute is defined as:
`day: { type: 'number', required: true, padding: { length: 2, char: '0' } }`

And in the primary index, the SK is defined as:
```
sk: {
  field: 'SK',
  casing: 'none',
  template: '${day}',
  composite: ['day'],
}
```
With this request:
`counts.query.primary({ '2022-05' }).gte({ 9 }).go();`

I get this error:
> One or more parameter values were invalid: Condition parameter type does not match schema type

Logging the the response from `.params()` gives:
```
{
  TableName: 'pjn-dev-v2-omw-pso-be-sst-coreStatsTable',
  ExpressionAttributeNames: { '#pk': 'PK', '#sk1': 'SK' },
  ExpressionAttributeValues: { ':pk': 'COUNT#2021-10', ':sk1': 9 },
  KeyConditionExpression: '#pk = :pk and #sk1 >= :sk1'
}
```
I think `':sk1'` should be `'09'`.

**Comment by PaulJNewell77** [comment]
Subsequent to the above I tried to up an update / add and the `Key` in the params is set to `{ PK: 'COUNT#2022-05', SK: 9 }`. Once again I think the SK should be `09`. But I may be missing something on the schema configuration.

**Comment by PaulJNewell77** [comment]
Thanks for the response. I have an existing table in a production system with large amounts of data, which will be hard to migrate, so changing the structure is not really an option. Besides, I feel the most valid use case for padding is when the attribute (`day` in this case) is a number and the sort key is a string. If they were both strings I could do the padding myself outside of ElectroDb. Hope that makes sense. Is there another way of forcing the sk to be a string in ElectroDb?

**Comment by rcoundon** [comment]
@tywalch - sorry to nudge, any thoughts on this?

**Comment by tywalch** [comment]
@rcoundon Thank you for the nudge, I needed this and I will have something this weekend 👍

**Comment by tywalch** [comment]
@PaulJNewell77 @rcoundon give 2.8.0 a spin, please let me know if you have any issues at all!

**Comment by PaulJNewell77** [comment]
I tried with 2.8.1, and afraid it still behaves the same for me. Maybe, I'm setting it up wrong? My day attribute is defined as:
```
day: { type: 'number', required: true, padding: { length: 2, char: '0' } }
```
And in the primary index, the SK is defined as:
```
sk: {
  field: 'SK',
  casing: 'none',
  template: '${day}',
  composite: ['day'],
}
```
Thanks

**Comment by tywalch** [comment]
@PaulJNewell77 On your `sk` definition try adding the property `cast: 'string'`. It should look like this:

```
sk: {
  field: 'SK',
  casing: 'none',
  cast: 'string',
  template: '${day}',
  composite: ['day'],
}
```

Here's a demonstration:

https://electrodb.fun/?#code/PQKgBAsg9gJgpgGzARwK5wE4Es4GcA0YuccYGeqCALgUQBYCG5YA7llXWAGbZwB2MXGBDAAUKKwBbAA5QMVMAG8wAUT5V2ATzABfbhiiSwAIkRwAxlQMwARsYDc481D64FVBjYSkAvCc1QqBgA+h5ecMF8DJJwDuLAwGDOqOpCbBxgAAYwDJqZYAxCDGB8qJI2mKLOrgrJqZFlYH58cCyq6loAFKJgSj29YJKwiABcfQMD-BpUmmPGHrgA1rjG+P0TAG6YuFgucwCMq+sDxBgbWOZwcwuLDNLSxsc6axMMVFZYNqhUeGOKx70huo6H8AQMZtIriY3Ng+ABzI4TCbkNBYcgwMZWdBg55gnKzJRgMG9CFQgDkpXKmDJhGJZDgqPRmIw6FpSIG0gYMBgWHhfyJ7Im3nhHDGACY2YLeuZGBgxmSAAxkgWCvQ4p4vAa8+AAD1+4yR0mwkiYBP+Uuki1BUt6XBwCAxJktiJtzhkUB2PzGAG1jECOMYALp03FSpbWm12xCOslLGl06WFXlw+V8FxweM2sA-GQIN7kgAkinxOkzrsKVHlMOTZalbtknqh3rJ+LJgc17J06omXd6ocJYW8ulEAEpHKIEklAqlWOxONlcvlCgUiB94VUXG4pykaMEYU0Sq12tNNN1euaBkN4AgIxMplproVli7NttdnwDi+TphzpdH0s7geDVjjeD4vh+XBb0vFxRQNdlSTmat4S-ZEGVQNE4EdLE4BxDsBnxfk6QQsBYzXOEaRVdkUXQplsxZOBJXZTluWTQis2FOFYIlSjBRlJh5SVHieyE4cezw7U4D1SC4I5Y1TSgiZLQUpEowdOZnTw9l6w9dgmz9GC6CDENNJOK0ZPZVSYzjEyJnMJM+RItMWlrQUc2kPMvRIosSxcrSKyrMjfKRbTGx9FtcjbGzRKRXsBli-tlEHUguzHJxp13SkADpzHIfNOmUf0QRIsUFTFMUAFoFQAVgogiwAATl0EdMrhKBOlSuoMrKTK0EwTRMqNKRTXywYDPlEqysqmqmpan4RrqxqdGa1r2vHTrcD3KxstyuaCrG4rSoq6ratyeV6uVJaWrajr0o2mEevQDB+sGk0npGwrxsOqaLuW3awDqslzpmlaxyAA

**Comment by tywalch** [comment]
@rcoundon tagging you as well

**Comment by rcoundon** [comment]
Thank you, Paul's on leave this week and was closer to the detail of this but from my perspective it looks good

**Comment by PaulJNewell77** [comment]
Hi Ty, yes, the `cast` on the SK is what I needed, thanks. This feature works for me. Hopefully will be useful to others - definitely worth adding to the docs. Otherwise happy for the issue to be closed - I'm sure you'll be relieved 😄
