### ISSUE TITLE
GSI using existing attribute as its SK results in query with an erroneous filter expression

### ISSUE THREAD

**Issue by PaulJNewell77** [tywalch/electrodb#238]
**Describe the bug**
If a GSI uses an existing attribute as its SK then queries are generated with an erroneous filter expression. In the playground link, see that the 'between' condition is expressed in both the KeyConditionExpression and the FilterExpression, the latter of which shouldn't be present.

**ElectroDB Version**
2.5.1

**ElectroDB Playground Link**
[ElectroDB Playground](https://electrodb.fun/?#code/PQKgBAsg9gJgpgGzARwK5wE4Es4GcA0YuccYGeqCALgUQBYCG5YA7llXWAGbZwB2MXGBDAAUKKwBbAA5QMVMAG8wAUT5V2AT0IBlTADcsAY1IBfbhiiSwAIkRwjVSzABGNgNzijUPrgVUGFwRSAF5bTShUDAB9AKC4aL4GSTgPLx8-MCMEYwBrITC+OBZVdS0AClEwJSrqsElYRAAuGrq6-g0qTRaAcgBhHKNcnvxatv1MXCwfXoBGADoABnnZkbG64gxDE16GBjW201G2hionLBdUKjwWxXXqo3JTuBgAEWfbsC7pOF6-bD4AHMRmQ4GgsOQYC0nOgwEd7mAYKcGMQqABJKFKL6aH5-c5AkHkcGQ6EYWHwtrVBiOLCGLoYz7fX5gHr-LAEwhE1AQl6k8nHSl+U6oXCMnHM1n44GcsHcklfMlmAVtEWYACCgI6YtxLLZHNBxN53AYCGIcOVdSoUFy-G1Er10oNcqNMKV6wpdXZ8AAHjdWpTpNhJExuv7KWBpLlPlwcAhMT0AAoAaRB3hkUCm1xaAG0ekiAqiMSCetSNHTNEWALqEa4yBAfFkAEkU+ZRcHRMFMAGJm6XaVoMaZUyj2YDenwfHAeuaEdVcFGsTHEPHHnBnm9nqmrLJM8zc6v1+9rj1q184HWGz1mwfrhvrkPCEYR0Dx5Ppx7Dhbqi5NEe21RblnMAvTgb1egAcR0NFVi-OpI2jWN41bQsYC3dNdxzPNkRQk8a3PaR6yzJsW2w9tB2HKYXxZCcinfWC5wXZQlzjXobxeI8p0fbcM3YPcejYu8p1PWsCMva8nlvDiHyyZ8x2ot8Z3DD9FJU5Q4mCOFRAASk8URsjyXB5jQTBNCA+Yfz-VFymUZCyPjV4dFWOEtLMlx2xYEg+GsrIJPYy8ACZFn8-yAFpFgAVjC-yABVZn8ppFkWOisQEjjekC4KwsioLYvixL3xc8NqnmQEoG8rBAQncgAHkWCKDBcDoLBpD5MwdKAA) 

**Entity/Service Definitions**
See playground link

**Expected behavior**
Query does not include a filter expression

**Errors**
```
ElectroError: Error thrown by DynamoDB client: "Filter Expression can only contain non-primary key attributes: Primary key attribute: createdDate"
```

**Additional context**
none

**Comment by tywalch** [comment]
Hey @PaulJNewell77 

This is a near identical ticket to this one: https://github.com/tywalch/electrodb/issues/228

Would you mind if I closed this one to consolidate the work under one ticket? Is there parts to this one that aren't covered in that one?

**Comment by PaulJNewell77** [comment]
Sure, hadn't read the detail on that one so didn't realise they were related in solution. They look the same so by all means close, thanks.

**Comment by tywalch** [comment]
Thanks @PaulJNewell77!
