### ISSUE TITLE
Sort key ignored for collection with clustered index type

### ISSUE THREAD

**Issue by thobson** [tywalch/electrodb#252]
**Describe the bug**

Probably a misunderstanding on my part, but I understood that a clustered index would allow me to query collections across both the PK and SK. I created two entities (user and item) with a shared clustered index. The item entity also has a SK of "itemId". When I try to query using `App.collections.items({ userId, itemId })` electrodb is pulling back **all** users and items, ignoring the SK. Please see the playground example.

**ElectroDB Version**

Specify the version of ElectroDB you are using

2.6.0

**ElectroDB Playground Link**

https://runkit.com/thobson/6489d8c70da8600008f716f1

**Entity/Service Definitions**
Include your entity model (or a model that sufficiently recreates your issue) to help troubleshoot.
```
let user = {
	model: {
		service: 'app',
		entity: 'user',
		version: '1'
	},
	attributes: {
		userId: {
			type: 'string',
			required: true
		}
	},
	indexes: {
		primary: {
			type: 'clustered',
			collection: 'items',
			pk: {
				field: 'pk',
				composite: ['userId']
			},
			sk: {
				field: 'sk',
				composite: []
			}
		}
	}
}

let item = {
	model: {
		service: 'app',
		entity: 'item',
		version: '1'
	},
	attributes: {
		userId: {
			type: 'string',
			required: true
		},
		itemId: {
			type: 'string',
			required: true
		}
	},
	indexes: {
		primary: {
			type: 'clustered',
			collection: 'items',
			pk: {
				field: 'pk',
				composite: ['userId']
			},
			sk: {
				field: 'sk',
				composite: ['itemId']
			}
		}
	}
}
``` 

**Expected behavior**

Fetch all users and items with the given sort key

**Comment by tywalch** [comment]
Hi @thobson 👋

So it's true that clustered collections allow you to use sort key composites, the caveat however is that you can only use "shared" sort key composites (left to right). 

So in your case, since on of your entities has no sort key composites, they have  zero shared sort key composites. In this case, you'd see more benefit from an "isolated" index 👍

Let me know if you need anymore detail, or have any follow up questions

**Comment by thobson** [comment]
Thanks, that makes sense
