### ISSUE TITLE
[Feature Request] Surface specific AWSError code

### ISSUE THREAD

**Issue by amandine-perichon** [tywalch/electrodb#253]
Would it be possible to surface AWSError codes, e.g. ConditionalCheckFailedException?
We'd like to easily check why the operation failed, to be able to handle specific use cases differently. 

For instance, if MyEntity.create(input).go() fails due to a ConditionalCheckFailedException, this means a record already exist, in which case we return a specific error message in our api.

**Comment by Euclidean-Dev** [comment]
Hey, have you tried the execution option .go({ originalErr: "true" }) and checked whether that gives you the error response you want?

**Comment by amandine-perichon** [comment]
Thank you, that's what I was looking for!

I looked up the Error documentation and Conditions Expressions documentation and didn't find it there. 
I now see this is under the specific queries and mutations that have that option available.

**Comment by amandine-perichon** [comment]
Closing the issue.
