### ISSUE TITLE
Operator `contains` doesn't support List and Set attributes

### ISSUE THREAD

**Issue by zirkelc** [tywalch/electrodb#255]
**Describe the bug**
The `contains` operator doesn't access arrays as attribute, even though DDB supports `contains()` on String, List and Set [^1]. 

![image](https://github.com/tywalch/electrodb/assets/950244/6d8d8037-2bd3-41da-b5b9-6458c9bb386c)

**ElectroDB Version**
2.6.0

**ElectroDB Playground Link**
See line 260 in [Playground](https://electrodb.fun/?#code/PQKgBAsg9gJgpgGzARwK5wE4Es4GcA0YuccYGeqCALgUQBYCG5YA7llXWAGbZwB2MXGBDAAUKKwBbAA5QMVMAG8wAUT5V2AT0IBlTADcsAY1IBfbhiiSwAIkRwjVSzABGNgNzijUPrgVUGFwRSAF5bTShUDAB9AKC4aL4GSTgPcVAwABUGXABrITUNKk1hMW9ffxz8sDC+OBZVdS0AClEwJTb2sElYRAAuDq6u-iLNAZsAvNwbfE6h-UxcLB9xgEYZua7iDEMTccnchmlpG03TWaGGKicsF1QqPAHFTfaH5KeXruLpOHG-bD4AHMNkMhuQ0FhyDABk50J9zp8Dh9QV9ND8-jcgSCUWQ4BCoTCMHCUQiUdJLAArBxUZE476-Wz-LBYi448GoSFwaFgWFweGsoaoba0lH0jEA4EC0Hsznc3n8xHsYIi0FixmYyWfdoygk8olwKXtUmg+C4IzYaQaFaDOlohk2JlYhUovxXIUqobAYBgIWkBh8MBMDAMEpUKA8u2BgP8VCSLUR9FgADaNigPz4M1szIAtOSoIDyLhpoRU3xs3QoAgYJmbEYEFBiNWALqBoTlPyGrrwLgMSg02xp-inEmd2TMmge1GJmx8WMuTDYobGoYBQG4SevO1-OBUReg9hwSTr9US4eg5ddbySFLqY-PHEJ+0ILB+PdDA9HjdT+2SI5v0F5j88g4He8aCsKNoPiuW4nsywJgV0F4Pi4sBjJBUGbtOjrwRhRoIaY8YESOnx1g2XJfmqDoav+7T6Awz4wFcDLAEmAAM2YAJxNooAAspjZmxnHcQATPxglcYoonAJ2SFgOacBMTAACC-b3ra06zpI84YDRYDdr21ADM0ACUNQAHxgAAIkxAB0fBQCwJmdu0Xpyf69kKPO3SwFgXA4DAgZcA8GByeQinxmFMAAPJ8AgaHysRKKoNIjEPMpqnxpRmnabprksFcRicFwchyYwQJ4Dy4b+iUVw3HcDzxvlVCFeMIC5d6xAKEYUTkOoPJSHgAQyKwdD8D6KXhQ+nVGaZIQWdZDx2Q5TkRQp0WxfF+rwmcUrMvAAAejzoe0eZUo4oEPtIuRfu0fmINyNhXbp7RXrISwPAMKZvJINhNoRzlENdx2gndVZ-Lkz1gK58lMXJVhvQeYC5HAmhCMVIXSEwGj0UQcgKMjJRoJgIEIa9DYHp9j2UtSNYHL9hHOqCORLICdTcmpKLQ5WwSOMsviBgg9YNOjKDoLwQgMOaDZCJIfZYNIwRgCM7Akw+3iC9SfPjMzWCszeNC6XtcD7eMa5YKsV3Zmbqx5NmRv7bpV03VD3q-tIlVgBEURgAA4joACSYAABI5HQwAAApYyrPhIyjCGgw91tPQDL3w+TH3JjYvo6X9D6ye0eTO65bse17IV+4HABK-qAnAwA6HjseaPHOBg7Y1t5JDZPvQyKaulQQr03njNDC4ku5PWgJfsXRwexwpAV2ASQpGAMdl1ZmjL1AlkAEI8oEwTxvbptLMJltm8Jtv247QMcziCcn1gZ8QyncMyOnvdU1AZ27rnOL54DZ2D926n07q-buFNM7fRrKRRsv0AZEXPGcToxplBxEVgRYynhRAZAAKrbAKE0YopRRDtgUNnIQtR6iNFGK0dod8ejwAQJOZWxRxjZ3-NsXY9oDhHBOJ2BYGAljWhsOsHamxarYHqkdO+rwFKSAojBKip4R5dGzoorC1FVHakrAyWR35KbwH0DWYgfBlg6RLK6LgXAazkmZEYeW9FfqtjhhUAG00wDNCKMqIgGpZoWX0Z6DqDAFguPttwEqr0mAvh8AhcgA8MABiTAhdoNgjGQ1SaY8xGT1QMGsTkqm9jHEIDPA+JsNl7ZRS4F4pUcAsH-XjLXfszRj5LznJgfxwMwQ7iiEklJth0mv0yfwbJQzcn5LGYUvgDjMYlIQk2JM9sWwAB9lkDnnjpTww9Eqgl-EkWuGANH2mwv+WSfkhFUAAHLJD0ZlJRJztFgAQDkK5NyjnijgqUxCnYuCUAQNclI7zYIsnjK5OogiiA7jAHRBA6A56jT0lcQIOQ+RTR3DNcyPoBBwD8mzAG0N6LdWeQ8bgfyl43NXgGeJvAYWNPRZ46IhBFDnL8ACg0TyXlstMJ0wJXR4m9LAAAAwACTMshKyilAB+SVtgbDmFFc8iVK9pWytMIKmyNxJAmS2f-R5eY-I+N5ZRN2jtLBAQ0DIhC0gKxhmdphY5WiMIAPaC4ZYdrHwfKdE61+9YjBXC1l01U9zHVQUQSSPVzI2ZApsNVL5RofncwcnBaNnVDYPE-MCnC54E2CwcosFNO402HmPMoz5jyYZpRUtG7KC4Ab6T7BiuaVlbL2UcsZAGkUYpxUJMSbNnxkqpS5FWwNWV2kWMagVOgrVdIeJMpihacAlpto7WtLtm1e1LnEe+bFh0Lq7MPNpPdKJ1Y8ytHwcYchAT+iwAAL39T4G+zsIEZy+vI+BLd7rjCeg0qat9SZpx7pTDhTZX7AIdBDBmOzwKYC-CezWIidZ6xGMWI+O7H4W1yFbJYNtMPXwBk7QNqd36AczsB0DrdE7Ye-Xndxf6MJgY7i-f9xHIFJj-uGjjiEUGsjQQfMwoh6mkJ8H4QMxwahL2oXoHYxg4DNGUBQwgBwhDcuwRkAA6tgElRNxYe1rnUYMJLMbBhSMFIQMd55kF1nQBQIgvDCf8PI8TNgCwkAzJ4MhPpthOZgDZOgqBN50DSB5061InPeHIEF+z+88hOZ4gAVmzAANkS8JViaR0gdUbgTUWmASjlBgNHfmTBSAsq6oqoQzJVCnssLvUQSmbLaebu0GyY8jAT3zHJsAIXHBgG5Z0GyLBRrkGaHJ1cuBzhKHKAEZk43OlTYYDNrxDA1wlhhegGwxljKdC9ANobsnRu1Im4oebM3uWYpO74GpVBggllSsi4gG2tvNcBFAOTch4CHLAAAclNEYL7KnRBAA)

**Entity/Service Definitions**
Include your entity model (or a model that sufficiently recreates your issue) to help troubleshoot.
```
{
    model: {
        entity: "my_entity",
        service: "my_service",
        version: "my_version"
    },
    attributes: {
        prop1: {
            type: "string"
        },
        prop2: {
            type: "string"
        }
    },
    indexes: {
        record: {
            pk: {
                field: "pk",
                composite: ["prop1"],
            },
            sk: {
                field: "sk",
                composite: ["prop2"],
            },
        }
    } 
}
``` 

**Expected behavior**
List and Set attributes should be filterable via `.where(({tags}, {contains}) => contains(tags, "value"))`.

**Errors**
```
Argument of type 'string[]' is not assignable to parameter of type 'string'.(2345)
```

[^1]: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.OperatorsAndFunctions.html#Expressions.OperatorsAndFunctions.Functions

**Comment by tywalch** [comment]
Hi @zirkelc 👋 

This has been added to `2.7.0`, let me know how it works for you 👍

**Comment by zirkelc** [comment]
Looks good! :+1
