### ISSUE TITLE
BatchPut overwrites timestamp `createdAt`

### ISSUE THREAD

**Issue by zirkelc** [tywalch/electrodb#270]
**Describe the bug**
Doing a Batch Put operations overwrites the timestamp attribute `createdAt`.

**ElectroDB Version**
electrodb@2.7.1

**ElectroDB Playground Link**

[ElectroDB Playground](https://electrodb.fun/?#code/JYWwDg9gTgLgBAbzgUQHY2DAnnAvnAMyghDgHIBTAGwoGMZiATAIzIG4AoL2iVAZ3gwAhsxpwAvOWp0GEdt14C4AZRjQKAGQi0hGRRLioKAdxTpMWABQc4iG7bggIjagC47Dh3wpQAbsFoKdzIAWSEqKlV1ABFgKBloLDIAGntPCnNsYLCIqPiUtIdfHz5gXmCARgLPXFTPXQZgZgBXGAo+dwRC21oLAElGTu6HbDAg8gEoYFQAc2rPB3iAR2a4ikG4BmaKOoXa4ZBwqgGhhZGsMeDJ6bnds+XV+I2tneH9s4F1E48zzYvxsjXWbze4UFZrZ5QbZ3BzvBYtYBURg3b5dX5-S4TRrAmGeB4Q9wvXF4YnNVCYVHDWyjAFA25UuD4p6EqGvM5wzw6NozRKnX409wAbUBYEwFDgn3yyXIBAgzgA9DwCAQKBQUjK5Yx5SAKOF1WRaFQIDAABY3fXSejEcm0Pj6lxgISwHXofUgYB8WhkAC6xNsTPWLOhb2JNCE3jQjGiunGaP5-yu2Pp6IDkOD7OJ8XQfLOAqxUxxDNTQbZv184WAjBj7nlAD1LAAdRgAagbADomwgAEy4ACUABJ5cSOQ5kZ6IGSYDmFnnAUmQQti4Rwt4-XAXAQhM0qFPyAAGNt7vcLzzlqiV6twOuNlvtzs9gdDkPDWjxGOMACCu7juYT5FQzQgMwPgnosuqMAA8qgVBYCWa5LkSDIbluO7uJYvYSAAfHA0ZtG2qAQMY6Frt4u7oVhOExvhhHEc+ZzNGAVZtJ+34MrOAFASBa7GLotAmsEABUoH+mCjyBpsrJrsh25kRh4jYbhFDUURvYkRQskUYpym0RmhQjtMLgAB7tNOtiSiZPxnGAADWpkLAQwDUBsZA2cJDg8OAEClG0QoGv0jBukcAw+muI6eHwtmWb8DlOVc1luT0JCQN54zCgiSIogF0pzl8AW+gyYUksMZKYB0UWeAZFCGcEMwehUNkALQzKUFQRQ1lWGW5Nl2Z4MVIjVdWuWuiWeSlvmHBEwX5eihVmZFP7RY5-XkM1wCtfFw1wB5yVir56XIrMwXZSVMBTaFw6hrq3hlQtFWoEZA18F2jWrV2bUdV180MrYfXObVT1Dd9W1JV5u1wMK5lnQVJFfeiP1LX9pRvRtQPbaDPng2QYYRvdikhdDdGwrscJIMIojivsvacGkeSaNouhlPwbZgK0liCoUt1bf5wRaHwH6zNIfBVMSkPORoDSaE6UBYHaxITccznIOGMAAAoQNMbSgftmXBAAYgAzAALKBJ3fGQQjCy+MY8tLwSygqSoqmql3hhQkaKcEXZ7l2XYNXu+sNT7oFZruZCGwArEeh7HjCI6c702Bm7z-MzILlsfGo8RmyE2gmkIABSEDtKB8tm0rAhqxrzvDNrh3OQb4cm+Sp3OUIXagVyFA27BGoOxAyqqqB2Nu7jl5kF7XYVH7U9B5mGShxUkcHkeC5wt6vZtjy6HU4l-DwPEfAyQYtNaFyjN8Jv6lsxzL7c+QycCzQQugaLPMS+LUDS7LBxBYryuV+gauZxa4zDNgbY2scYTxzvmQB+qcn7pwWK-cgOc+IFyLt-M4pc-4V3VoArWqwMp1z1vrRukD7Dr03hAbeQA)

To reproduce the issue locally: [Gist](https://gist.github.com/zirkelc/eb4e5192970f2a9670bab3089f8b3293)
 ```ts
for (let i = 0; i < 2; i++) {
  await StoreLocations.put([
    {
      cityId: 'LosAngeles1',
      storeId: 'LatteLarrys',
      mallId: 'EastPointe',
      buildingId: 'F34',
      unitId: 'a1',
      category: 'food/coffee',
      leaseEndDate: '2022-03-22',
      rent: '4500.00',
    },
    {
      cityId: 'LosAngeles1',
      storeId: 'MochaJoes',
      mallId: 'EastPointe',
      buildingId: 'F35',
      unitId: 'a2',
      category: 'food/coffee',
      leaseEndDate: '2021-01-22',
      rent: '1500.00',
    },
  ]).go();

  const { data } = await StoreLocations.get([
    {
      cityId: 'LosAngeles1',
      storeId: 'LatteLarrys',
      mallId: 'EastPointe',
      buildingId: 'F34',
    },
    {
      cityId: 'LosAngeles1',
      storeId: 'MochaJoes',
      mallId: 'EastPointe',
      buildingId: 'F35',
    },
  ]).go();

  /**
   * 1. iteration:
   * [
   *   { createdAt: 1689923939109, updatedAt: 1689923939109 },
   *   { createdAt: 1689923939109, updatedAt: 1689923939109 }
   * ]
   * 2. iteration:
   * [
   *   { createdAt: 1689923939327, updatedAt: 1689923939327 },
   *   { createdAt: 1689923939327, updatedAt: 1689923939327 }
   * ]
   */
  console.log(
    data.map(({ createdAt, updatedAt }) => ({
      createdAt,
      updatedAt,
    })),
  );
}
```

**Expected behavior**
Only the `updatedAt` should be updated during `put`, but `createdAt` should not change.

**Additional context**
The ElectroDB Playground shows the Batch Put operation as two single Put operations and one BatchWrite operation. Maybe this issue is related to that.

**Comment by tywalch** [comment]
Unfortunately this is a limitation of DyanmoDB, a `Batchput` will always overwrite existing records

**Comment by Euclidean-Dev** [comment]
Damn. I just got stung by this too. I'll update the docs and submit a PR.

**Comment by tywalch** [comment]
Hi @zirkelc and @Euclidean-Dev 

This functionality is actually expected for a batchPut, since it makes a call to dynamodb batchWrite. 

My suggestion would be to use `upsert` and flag your `createdAt` attribute as `readOnly`, which will then only modify the attribute if the value does not exist 👍

**Comment by Euclidean-Dev** [comment]
Thanks @tywalch.  I'll do that.

**Comment by Euclidean-Dev** [comment]
Hey @tywalch, now using upsert but that still overwrites createdAt, and it's configured readOnly.  I'm struggling to find the problem.

Running v2.9.3

createdAt: {
  type: "number",
  readOnly: true,
  required: true,
  default: () => Date.now(),
  set: () => Date.now(),
}

**Comment by Euclidean-Dev** [comment]
I just spotted the below in the docs...  and createdAt is a composite on global secondary sort keys.  Not sure where that leaves me... do I have to use a patch? 🫤 

Note: upsert will apply a dynamodb set operation on all attributes provided. If an attribute is configured as readOnly, ElectroDB will apply a if_not_exists condition to prevent overwriting the existing value. **_The exception case is if the attribute is a composite of an index, in which case it will NOT be wrapped with if_not_exists()_**
