### ISSUE TITLE
Secondary index keys not updated when using composite attributes from table's primary index

### ISSUE THREAD

**Issue by misterjoshua** [tywalch/electrodb#286]
**Describe the bug**
When I use the update mutation to create an item, the secondary index keys are not included in the update even though all the attributes used in the secondary index are part of the primary index.

**ElectroDB Version**
`2.8.2`

**ElectroDB Playground Link**
[Playground Link](https://electrodb.fun/?#code/FASwtgDg9gTgLgAgN4IKIDs4jgTwQXwQDMYowEAiAUwBsqBjOUgEwCMKBuYYeqdAZ0QBZAK40sAEXBUBIPgEMaASXTMqAD3ms6AZRHkAvAnRUA7mkzYcACiTAECMFDU0AXMnsOE-KjABuIPRU7gDkcFSCIQA0ng5+vvxy6KEAjNGxCDJYuKGi4iBSYDKJCsqqGlq6+ukO+DEO8nBMIKwi4fzudl4IzOApnQi4EMEIIYIwIOgA5iEE9V69YABMA0MjY83Ts3UZiwDMqzjDoeOTM3MZ8lNTMFRTjSMoayebM1EItwCOIiC3zO5MERUC7dYYTZyHY6jU5bd5fH5-AEwIEgrz8fSQ9bofSsXzRHpUIjyMRwdwABjhVG+vyo-0GyOBO26vBEmExoWxYFxMHxaiJJPJlOpiPpKKZqMmanUEU6GVYOAAgtdbvdwrLug4IABrdUahxEEC0OkhAAKAGkanqELxIFBEmqEABtEKLNLvF3gJb4j1gPbeq43O4PEIAXXm3XF3X4Oo8VuIhpoxp0FvDGpt0HtI2dYLkzFDqdqqZ2cpwhX6sY1ko0oQA4jolG6MpqY10rQajbX6ylzZa9em7dgsz60mGm6ioy2x-qE8a6w3k7202QM4P3NnfLnvYsve79v7lUHwvmx5GLiXCisK90q+pO0od2Ptbq9e3E3elj2C15+5m1z6vaOeqng40bPhqr6zvWSwLl+Dg-quTohDmzhbn0qG+vugaqlQx5AUWMTnuABxXl4N53n6X5PiR3QQeRn5Ttay4Dg6zp7oBGrAd4k5xrRoxznsMEMfBLFIRuKG7mhEnLNEIQBiqwbsRG+GeDsdTIIMlQjBQOBQCIMAAPpwJp+noPIRQUAQACUXDcAA9LZCAmiwIhBPwgwABbAnO6DmrZybxka-DAHkkjSLIpQqFKml6GAAB09C3A8tieK6oT0CIghkL4+nyJa25pRlcBZQZ8j6VkVj6aweVEQVmVFCVZWWLglX6X4jYNAe2GhO0cCWshxpFcw8g4Ok+CWbFUxQNY1l2Q5EhQBExhQIgEDOUEHlefWPlmn5ZoBYmQUhQUYUlKZZRRdoVAxbFIgQEN4TJQ4qWjOldXZbl8z5S9hXFTljXZDglXVb6tVFfVf3lc1rCte1CByYe6w9X1YkDc4w2jeN8jMMwtiMaypIICk7zomA7gAKxklZE1TdZQA)

**Entity/Service Definitions**
See the playground link: [Playground Link](https://electrodb.fun/?#code/FASwtgDg9gTgLgAgN4IKIDs4jgTwQXwQDMYowEAiAUwBsqBjOUgEwCMKBuYYeqdAZ0QBZAK40sAEXBUBIPgEMaASXTMqAD3ms6AZRHkAvAnRUA7mkzYcACiTAECMFDU0AXMnsOE-KjABuIPRU7gDkcFSCIQA0ng5+vvxy6KEAjNGxCDJYuKGi4iBSYDKJCsqqGlq6+ukO+DEO8nBMIKwi4fzudl4IzOApnQi4EMEIIYIwIOgA5iEE9V69YABMA0MjY83Ts3UZiwDMqzjDoeOTM3MZ8lNTMFRTjSMoayebM1EItwCOIiC3zO5MERUC7dYYTZyHY6jU5bd5fH5-AEwIEgrz8fSQ9bofSsXzRHpUIjyMRwdwABjhVG+vyo-0GyOBO26vBEmExoWxYFxMHxaiJJPJlOpiPpKKZqMmanUEU6GVYOAAgtdbvdwrLug4IABrdUahxEEC0OkhAAKAGkanqELxIFBEmqEABtEKLNLvF3gJb4j1gPbeq43O4PEIAXXm3XF3X4Oo8VuIhpoxp0FvDGpt0HtI2dYLkzFDqdqqZ2cpwhX6sY1ko0oQA4jolG6MpqY10rQajbX6ylzZa9em7dgsz60mGm6ioy2x-qE8a6w3k7202QM4P3NnfLnvYsve79v7lUHwvmx5GLiXCisK90q+pO0od2Ptbq9e3E3elj2C15+5m1z6vaOeqng40bPhqr6zvWSwLl+Dg-quTohDmzhbn0qG+vugaqlQx5AUWMTnuABxXl4N53n6X5PiR3QQeRn5Ttay4Dg6zp7oBGrAd4k5xrRoxznsMEMfBLFIRuKG7mhEnLNEIQBiqwbsRG+GeDsdTIIMlQjBQOBQCIMAAPpwJp+noPIRQUAQACUXDcAA9LZCAmiwIhBPwgwABbAnO6DmrZybxka-DAHkkjSLIpQqFKml6GAAB09C3A8tieK6oT0CIghkL4+nyJa25pRlcBZQZ8j6VkVj6aweVEQVmVFCVZWWLglX6X4jYNAe2GhO0cCWshxpFcw8g4Ok+CWbFUxQNY1l2Q5EhQBExhQIgEDOUEHlefWPlmn5ZoBYmQUhQUYUlKZZRRdoVAxbFIgQEN4TJQ4qWjOldXZbl8z5S9hXFTljXZDglXVb6tVFfVf3lc1rCte1CByYe6w9X1YkDc4w2jeN8jMMwtiMaypIICk7zomA7gAKxklZE1TdZQA)

**Expected behavior**
I expected the `update` mutation to generate the secondary index keys.

**Errors**
I didn't receive any error message, but the result is that the update causes an incomplete record to be written when it should have been possible to write a complete record.

**Additional context**
Maybe I've misinterpreted the docs, but I was going off of this section:

> In the event that a secondary index includes composite values from the table’s primary index, ElectroDB will draw from the values supplied for the update key to address index gaps in the secondary index.

Source: https://electrodb.dev/en/mutations/update/#updating-composite-attributes

I'm a fairly new ElectroDB user, so forgive me if I've missed something obvious. Thanks for your help.

**Comment by misterjoshua** [comment]
I updated to ElectroDB 2.9.1 and I tried the `.composite()` method on an update, thinking maybe that would include the secondary index keys. But unfortunately, it appears the condition expression constraint prevents the item from being created.

Here's a playground to show what I mean: [Playground](https://electrodb.fun/?#code/FASwtgDg9gTgLgAgN4IKIDs4jgTwQXwQDMYowEAiAUwBsqBjOUgEwCMKBuYYeqdAZ0QBZAK40sAEXBUBIPgEMaASXTMqAD3ms6AZRHkAvAnRUA7mkzYcACiTAECMFDU0AXMnsOE-KjABuIPRU7gDkcFSCIQA0ng5+vvxy6KEAjNGxCDJYuKGi4iBSYDKJCsqqGlq6+ukO+DEO8nBMIKwi4fzudl4IzOApnQi4EMEIIYIwIOgA5iEE9V69YABMA0MjY83Ts3UZiwDMqzjDoeOTM3MZ8lNTMFRTjSMoayebM1EItwCOIiC3zO5MERUC7dYYTZyHY6jU5bd5fH5-AEwIEgrz8fSQ9bofSsXzRHpUIjyMRwdwABjhVG+vyo-0GyOBO26vBEmExoWxYFxMHxaiJJPJlOpiPpKKZqMmanUEU6GVYOAAgtdbvdwrLug4IABrdUahxEEC0OkhAAKAGkanqELxIFBEmqEABtEKLNLvF3gJb4j1gPbeq43O4PEIAXXm3XF3X4Oo8VuIhpoxp0FvDGpt0HtI2dYLkzFDqdqqZ2cpwhX6sY1ko0oQA4jolG6MpqY10rQajbX6ylzZa9em7dgsz60mGm6ioy2x-qE8a6w3k7202QM4P3NnfLnvYsve79v7lUHwvmx5GLiXCisK90q+pO0od2Ptbq9e3E3elj2C15+5m1z6vaOeqng40bPhqr6zvWSwLl+Dg-quTohDmzhbn0qG+vugaqlQx5AUWMTnuABxXl4N53n6X5PiR3QQeRn5Ttay4Dg6zp7oBGrAd4k5xrRoxznsMEMfBLFIRuKG7mhEnLNEIQBiqwbsRG+GeDsdTIIMlQjBQOBQCIMAAPpwJp+noPIRQUAQACUXDAAA9LZCAmiwIhBPwgwABbAnOSDoPg5q2cm8ZGvw7ytIgvCqNgSSZOoEC3PwJToHZDlxVQ8SYG59C3I00VQEQHnAoOYAAHTAHkkjSLIpQqFKml6CVIgQMwDy2J4rqhPQIiCGQvj6fIlrbh1XVwD1BnyPpWRWPprADURQ3dUUY0TZYuDTfpfiNg0B7YaE7RwJayHGiNzU4Ok+CWZ4xXyMwzC2IxrKkggKTvOiYDuAArGSVmXcJVCtd07WjJ1C29f1qaDUDw2jX1y3ZDg02Lvs80jYtMOTatrDrZtXhyYe6x7Za52XVMUDWNZQA)

**Comment by tywalch** [comment]
Hi @misterjoshua 👋 

It sounds like you're intentionally using "update" to create an item. To better understand your need, can you checkout the "upsert" method (https://electrodb.dev/en/mutations/upsert/) and let me know if that is capable of doing what you need? 

The "composite" function on update is for cases where a composite attribute _can't_ be set, e.g. because the property is readOnly.

**Comment by misterjoshua** [comment]
@tywalch Hi. Thanks for responding.

Yes, I am intentionally using `update` to create the item if it doesn't exist - but if it does exist, then the write operation should add a numeric value to a numeric item attribute. The DynamoDB [ADD keyword](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.UpdateExpressions.html#Expressions.UpdateExpressions.ADD.Number) lets you do this blindly if you know the rest of the item attributes at the time of write, which I do.

No, unfortunately, the `upsert` method can't do what I'm after, as it requires I know what value the attribute should be after the `ADD` operation, but I don't because I'm trying to avoid the unnecessary overhead of reading the record I'm updating, as reading the item increases the cost of the operation by 17% in the best case.

**Comment by misterjoshua** [comment]
@tywalch Yes, conditions looking like `(${name} = ${value} or attribute_not_exists(${name})` would work nicely in the interim, and I like your longer-term idea as well. Thank you.

**Comment by misterjoshua** [comment]
I took a peek at aec1f57 and had a comment about the condition expression. My comment is inline here: https://github.com/tywalch/electrodb/commit/aec1f57d403fed4adc4e0a427fd0641f061400c0#r125880163

**Comment by tywalch** [comment]
@misterjoshua Thanks! This hasn't been published yet, the fact this commit made it to master was a mistake in a local script 👎. When this is ready to be published there will be additional tests and I will ensure this missing paren gets added.

**Comment by tywalch** [comment]
I also would love to hear @sam3d weigh in on this too btw

**Comment by tywalch** [comment]
@misterjoshua 

Small update: I am rethinking this approach because it unfortunately conflicts with some of the goals associated with `.composite()`. I think the solution here must be adding the mutation methods to upsert.

**Comment by misterjoshua** [comment]
> @misterjoshua
> 
> Small update: I am rethinking this approach because it unfortunately conflicts with some of the goals associated with `.composite()`. I think the solution here must be adding the mutation methods to upsert.

Sounds good to me. The mutation methods on upsert could work well for my use case.

How do you think this would look, btw? Something like this?

```ts
entity.upsert(allAttributesExceptThoseInTheAdd)
  .add({ attribute: 1 })
  .go();
```

**Comment by tywalch** [comment]
I have opened this PR (nearly ready to merge) that adds support for `add`, `subtract`, and `append` operations on `upsert`: https://github.com/tywalch/electrodb/pull/296 🎉 

I will merge soon, likely tomorrow

**Comment by misterjoshua** [comment]
Thank you for all the work you've put into this so far!

**Comment by tywalch** [comment]
Just merged, here's a [playground](https://electrodb.fun/?#code/FASwtgDg9gTgLgAgN4IKIDs4jgTwQXwQDMYowEAiAUwBsqBjOUgEwCMKBuYYeqdAZ0QBZAK40sAEXBUBIPgEMaASXTMqAD3ms6AZRHkAvAnRUA7mkzYcACiTAECMFDU0AXMnsOE-KjABuIPRU7gDkcFSCIQA0ng5+vvxy6KEAjNGxCDJYuKGi4iBSYDKJCsqqGlq6+ukO+DEO8nBMIKwi4fzudl4IzOApnQi4EMEIIYIwIOgA5iEE9V69YABMA0MjY83Ts3UZiwDMqzjDoeOTM3MZ8lNTMFRTjSMoayebM1EItwCOIiC3zO5MERUC7dYYTZyHY6jU5bd5fH5-AEwIEgrz8fSQ9bofSsXzRHpUIjyMRwdwABjhVG+vyo-0GyOBO26vBEmExoWxYFxMHxaiJJPJlOpiPpKKZqMmanUEU6GVYOAAgtdbvdwrLug4IABrdUahxEEC0OkhAAKAGkanqELxIFBEmqEABtEKLNLvF3gJb4j1gPbeq43O4PEIAXXm3XF3X4Oo8VuIhpoxp0FvDGpt0HtI2dYLkzFDqdqqZ2cpwhX6sY1ko0oQA4jolG6MpqY10rQajbX6ylzZa9em7dgsz60mGm6ioy2x-qE8a6w3k7202QM4P3NnfLnvYsve79v7lUHwvmx5GLiXCisK90q+pO0od2Ptbq9e3E3elj2C15+5m1z6vaOeqng40bPhqr6zvWSwLl+Dg-quTohDmzhbn0qG+vugaqlQx5AUWMTnuABxXl4N53n6X5PiR3QQeRn5Ttay4Dg6zp7oBGrAd4k5xrRoxznsMEMfBLFIRuKG7mhEnLNEIQBiqwbsRG+GeDsdTIIMlQjBQOBQCIMAAPpwJp+noPIRQUAQACUXDcAA9LZCAmiwIhBPwgwABbAnO6DmrZybxka-DAHkkjSLIpQqFKml6GAAB0IgQD48C2J4rqhPQIiCGQvj6fIlrbulmVwNlBnyPpWRWPprD5URhVZUUpXlZYuBVfpfiNg0B7YaE7RwJayHGsVzDyDg6T4JZsXyMwzC2IxrKkggKTvOiYDuAArGSVmxVMUDWNZQA) showing its use, let me know if you experience any issues!
