### ISSUE TITLE
Feature request: Add Conditional Indexing Based on Attribute Presence

### ISSUE THREAD

**Issue by misterjoshua** [tywalch/electrodb#300]
**Description**
I'd like ElectroDB to have a conditional indexing feature to prevent unnecessary GSI writes & hot partitions for certain data models.

**Use Case**
I have a data model that supports up to five levels of hierarchical depth (lv1 through lv5). However, not all entities utilize all five levels. This leads to wasted GSI write capacity and creates hot partitions for GSIs.

[Playground Link](https://electrodb.fun/?#code/JYWwDg9gTgLgBAbzgUQHY2DAnnAvnAMyghDgCIBTAGwoGMZiATAIzIG4AoD2iVAZ3gwAhsxpwAvOSwQArlAD6w0RXmohICuy49+8AJIwKIAIIwAMhQBu1CXFQUA7inSYsACg5xEnr3BARGagAub19fChdsELIDI1MLayoyABofMOsoPmBeaIBGFLTfPgooS2BaCmiACWASoShaAAtyoSpYkABZAOoyQtxUsKEYBmBmGUM+EIRCrypLXKm4bDBKuAByAShgVABzNeS4QIIhGSoYELX9vAGwuDmAJkXl1Y2R3aujk7OLq-6Zu8sAGYnlgVhdNts9gdPqdzutfjcwnMACwgsHrCHvaEUY6wn4HP63AEAVjRL0xUMOOK+cMuBMR10K20CAA8KJNQrcQEJtlN-l4wABrPlEsIEWpURgXIX7fm+HjgCBZQwhADaazmuSuGss921c0B+ssyKNxLWAF0GWFCaK+MLOaLCBKpRjBbLHV4FZBlatVZa5bh-jawswsGZ5iLRcyKCyLqHw1qrb4hZHHeLqC6dbkZUmwl6lZhfVmLbnGY67anRenJRdNXb3R78z61Tq9QcdYb2yjTSWA0Gk-HdZWwtHY+tB225SmHVXnbXdTm5Z6SN7Cy2Hr3HcHbhWZ0Tq5mHvXS8vFc24OrNUbO+tu13LGb-Vv+-9B8C975R3Gw0CG0Tp9MHpOhm86AouQFNmuF4dpuorbmEu6AR6B6gceS5wJBKrQVe95trexo9k+cEvkSg6oh+XhfuOP4mqWAHoSh+HIuBjYrgWWGXgRRFEvBRT2khaZzkxaEQWx56cYm+F4TB96PqWgY8QOP6khRcBUWsg5mnR-EMUJOrEixjqYUWcxyQGpaIbpIH4cSImsWeUESUa0kGkaJrcbcCmeQyXk2kgShiIGACUnAcO08RWNQAB0tBQBQQwUG4SGahchhqOg8gyDIwCMA2DwXCAWDyHFfCyA0KjPHlQIXCVZUVJl2W5TcKIFUVtVyPVzzyGAxArLAWANgA9INJJqXwcAkJghiMHAzB0CcxRqTAGxwDIqAyMUM3bEszTjTG6hgDQUVwAYK3bTAjQUD4w2HEMQh+N0VBwKVO0UHAEQYNgSygm9tBCKgz0yGAkCwE61h3JFVDjRABBwM0dRQM0f1UNdI2BGAF0HGM8AOBQaxxXYEDwBtkJLYQ0A7cA40EGVAC0NCJHDtRQPUTRYFFqOoydsPSDIdwQBAgpwEMr1wGA4wTX1QzZKgBymUKg2mXawsE3NpPFDAHNeDdAAql1i8QyikFTSwOBAtM0zWcAAOp4wTDhCAIpMAOIAMp6HADhbIYGFCGAQi0K45NQMLqBc2tG0UDN8Msw0SOtBDiQHP9M0XW9-uwJgMtwIKFA4DTIf-e94DYFzpljagazwHwMgEOKgcfVQOBrcAACOMgUAcL1p7NylwG7HsOMAVBPY0Qjg40RNcxnn0y3wx16IErRNwcehrDNVDALnlPjWQsXxYYZCS3UGC8ITggQNPEDi1QCWi-LgqKw+ytDCM2PshzuBBVFOwQG4IVcCAA)

**Possible Solution**
I envisioned extending the index definition to accept a `condition` field with a function that can evaluate whether or not to populate the index fields. The idea is that if the condition function is present and it returns false, the pk & sk for that GSI are not written.

In the following example, for instance, `lv5pk` and `lv5sk` would be left unset and the `byLv5` index would not be populated unless the `lv5` attribute is set:

```
byLv5: {
  index: 'byLv5',
  // This is the new function
  condition: (attrs) => attrs.lv5 !== '',
  pk: {
    field: 'lv5pk',
    composite: ['lv5'],
  },
  sk: {
    field: 'lv5sk',
    composite: ['lv1', 'lv2', 'lv3', 'lv4'],
  }
},
```

**Comment by tywalch** [comment]
This is a reasonable request, let me look into the work necessary to get something to solve for this case

**Comment by misterjoshua** [comment]
Thanks dude!!!
