### ISSUE TITLE
UpdateExpression created by `.patch` doesn't account for custom attribute `field` value

### ISSUE THREAD

**Issue by thorhj** [tywalch/electrodb#319]
**Describe the bug**
When using a different field name for an attribute that is part of the partition-key, then a PATCH operation on the entity will add an column with the attribute schema key because the generated `ExpressionAttributeNames` does not take the attribute field value into account.

**ElectroDB Version**
2.10.4

**ElectroDB Playground Link**
[ElectroDB Playground](https://electrodb.fun/?#code/PQKgBAsg9gJgpgGzARwK5wE4Es4GcA0YuccYGeqCALgUQBYCG5YA7llXWAGbZwB2MXGBDAAUKKwBbAA5QMVMAG8wAUT5V2AT0IBlTADcsAY1IBfbhiiSwAIkRwjVSzABGNgNzijUPrgVUGFwRSAF5bTShUDAB9AKC4aL4GSTgPUW9fBQAVPCo1DSpNML44FlV1LQAKUTAlGtqwSVhEAC46hob+As02mypcm3x6juIMQxNe-r9B4Yb9TFwsH16ARhmO0yGOhionLBdUKbbFWdqurQBJGGPThq4cBGvbc8LorBh1jobC6Thev2wfAA5p8NlsvlAOJgrjcvncHk8bJC6Jg3h9wXCfn9bACsMDQQ1Nrd9AwEOhYXCwFjenxUJIXJgCbUiWDZnj4AAPPAUjpTKg8r7SADWArh90QiOFTK+3hkUEW-TaAG07BVCldBrZkdCPgBdDFfFmU3Ai9qU2rix7-IXSjqy2QK7FK-W3ZkGt2zI1G5RxYK9eyOSwAWg4ACsQ7kgwAmGxgUyiACUnlEOT8+S0twAdNIdkY6JVlC9NDDbAAWGOEbUYEs2UsAZljpgTWeIVALYBJZOxKwADHHm3Ds0xkrhKs2gA)

**Entity/Service Definitions**

```
const table = "your_table_name";
const TestEntity= new Entity(
  {
    model: {
      entity: "test",
      service: "test",
      version: "1",
    },
    attributes: {
      entityId: {
        field: "entity_id",
        type: "string",
      },
      otherId: {
        field: "other_id",
        type: "string",
      },
      value: {
        type: "number",
      },
    },
    indexes: {
      test: {
        pk: {
          field: "pk",
          composite: ["entityId", "otherId"],
        },
        sk: {
          field: "sk",
          composite: [],
        },
      },
    },
  },
  { table: "electro-thj-test-2" }
);

TestEntity
      .patch({ entityId: "42", otherId: "43" })
      .set({ value: 10 })
      .params()
```

**Expected behavior**
First of all, I would expect the call to `.patch({ entityId: "42", otherId: "43" }).set({ value: 10 })` to generate a query where only `value` is set. Secondly, I would expect all occurences of `entityId` and `otherId` in the query to be mapped to `entity_id` and `other_id` respectively because of the explicit field mapping in the attributes schema.

**Errors**
The update expression in the generated query is as follows:

```
    "UpdateExpression": "SET #value = :value_u0, #entityId = :entityId_u0, #otherId = :otherId_u0, #__edb_e__ = :__edb_e___u0, #__edb_v__ = :__edb_v___u0",
    "ExpressionAttributeNames": {
        "#pk": "pk",
        "#sk": "sk",
        "#value": "value",
        "#entityId": "entityId",
        "#otherId": "otherId",
        "#__edb_e__": "__edb_e__",
        "#__edb_v__": "__edb_v__"
    },
    "ExpressionAttributeValues": {
        ":value_u0": 10,
        ":entityId_u0": "42",
        ":otherId_u0": "43",
        ":__edb_e___u0": "test",
        ":__edb_v___u0": "1"
    },
    "TableName": "electro-thj-test-2",
    "Key": {
        "pk": "$test#entityid_42#otherid_43",
        "sk": "$test_1"
    },
    "ConditionExpression": "attribute_exists(#pk) AND attribute_exists(#sk)"
}
```

As you can see, the `ExpressionAttributeNames` for `#entityId` and `#otherId` are not `entity_id` and `other_id` as expected, but rather `entityId` and `otherId` as the attribute keys are called in the schema. In this case it causes two new columns to appear for the entity:

![image](https://github.com/tywalch/electrodb/assets/4330107/88a0ed84-0d38-4bcb-a59b-d9c60ce7742d)

I don't understand why they even appear in the `UpdateExpression`, but there might be a good reason for that.

**Comment by tywalch** [comment]
Hi @thorhj 👋 

Firstly, thank you for reporting this! I just published version `2.10.5` which should have your fix. If you check your playground link again you should find that the field names are correctly used. Let me know if everything looks good on your end and we can close the ticket when that is true.

> First of all, I would expect the call to .patch({ entityId: "42", otherId: "43" }).set({ value: 10 }) to generate a query where only value is set. 

Regarding this question, this is because `patch` simply uses the `update` method under the hood. The `update` method adds these properties because an `update` has the potential to create an item in DynamoDB. ElectroDB has hard constraints in place to maintain data consistency between key values and composite attribute values. Hope that helps!

**Comment by thorhj** [comment]
Wow that was quick, thanks a lot! And thanks for this awesome library 😁 

> Let me know if everything looks good on your end and we can close the ticket when that is true.

I just tested my code with the new version and it's working as expected now.

> Regarding this question, this is because patch simply uses the update method under the hood. The update method adds these properties because an update has the potential to create an item in DynamoDB. ElectroDB has hard constraints in place to maintain data consistency between key values and composite attribute values. Hope that helps!

Superb 💪 I just wasn't expecting to see them in the query, that's all.

**Comment by tywalch** [comment]
Great to hear! Check back in if you have any further issues 👍
