### ISSUE TITLE
Specifying `response: 'all_new'` on `.update()` returns `Partial<T>` instead of `T`

### ISSUE THREAD

**Issue by dankochetov** [tywalch/electrodb#329]
**Describe the bug**

Given this code:
```ts
const { data } = await table.update({ id }).set(updates).go({ response: 'all_new' });
```
Type of `data` is `Partial<ResponseItem<...>>`, whereas it should be `ResponseItem<...>`.

**ElectroDB Version**

`2.11.0`

**ElectroDB Playground Link**

https://electrodb.fun/?#code/PQKgBAsg9gJgpgGzARwK5wE4Es4GcA0YuccYGeqCALgUQBYCG5YA7llXWAGbZwB2MXGBDAAUKKwBbAA5QMVMAG8wAUT5V2ATzABfbhiiSwAIkRwAxlQMwARsYDc481D64FVBjYSkAvCc1QqBgA+h5ecMF8DJJwDk4ubmCoxBhCfnxwLKrqWgAUomBKBYVgkrCIAFxFJSX8GlSaVcbJmMb4xTUpAG5Y5nBNHrgA1gzS0m0dJV2YuFguTQCMxpM67TUMVFZYNqhUeFWKk4VYMAdHJQ3S-WAA5G7YfADmN2s1JeRoWOSnYFborzVVucojEzm8LporlU7lsni9zoUPqgvnAfn84ACSkDAZisAI4AAPfbVN4nMHgsDSIbkincHAIH43E7w2mFZwyKCzPZVADaTJgNwAupicedsVjXuLlGFvLpRABKRyiBi4TR8czcVDqjQuUoMPG5eUk5yuBTKGAbBi6MB+BgsfUKFqpAB0qGkFr2uWUZNuCxuunlzuIVC9YBB1xuyBYcH9OkDjygofIuFkrgjDAQCEimVjitEOnEkn1fEN9iAA

**Entity/Service Definitions**
Include your entity model (or a model that sufficiently recreates your issue) to help troubleshoot.

```
  {
    model: {
      entity: "user",
      service: "taskapp",
      version: "1"
    },
    attributes: {
      id: {
        type: 'string',
        required: true,
      },
      name: {
        type: 'string',
        required: true,
      },
    },
    indexes: {
      id: {
        pk: {
          field: 'id',
          composite: ['id'],
        },
      },
    },
  },
```

**Expected behavior**

Response type should be `ResponseItem<...>`

**Comment by tywalch** [comment]
Hey @dankochetov 👋

This is actually deliberate! Because `update` is an "unsafe" operation, in that it can result in an unintentional insert, the `update` response type reflects the (lack of) confidence the returned item will have all of it's properties.

The `patch` method (which condition checks the item is present) and `upsert` methods do return the full item typing for this reason 👍
