### ISSUE TITLE
Broken link in docs (Pagination)

### ISSUE THREAD

**Issue by davidhollenbeckx** [tywalch/electrodb#332]
**Describe the bug**
Link to Query options on the [pagination docs](https://electrodb.dev/en/queries/pagination/) leads to a generic netlify 404.

The linked url is https://electrodb.dev/en/queries/pagination/ but I believe it should go to https://electrodb.dev/en/core-concepts/executing-queries/

**Comment by fredrikj31** [comment]
It seems to have been fixed in this PR https://github.com/tywalch/electrodb/pull/352

**Comment by fredrikj31** [comment]
I think you can close this issue @tywalch, if it has been fixed 👍
