### ISSUE TITLE
Typescript Warning when Omitting Non Required Attributes on Create/ Put

### ISSUE THREAD

**Issue by fmvfelipemonsalve** [tywalch/electrodb#344]
**Describe the bug**
When the sort key for the primary index of an entity is an empty array, I'm getting a Typescript error with the create method for the entity, when I don't include non-required fields in the object I pass to the method.

If I remove the sort key, or add an actual attribute to the sort key's composite field, the error disappears. 

**ElectroDB Version**
2.13.0

**ElectroDB Playground Link**
[ElectroDB Playground Example](https://electrodb.fun/?ssl=15&ssc=25&pln=15&pc=31#code/JYWwDg9gTgLgBAbzgUQHY2DAnnAvnAMyghDgCIBTAGwoGMZiATAIzIG4AoDigD0lji0IqAM7wAshSi0AFgEN0aDNjgBeOKgoB3FOkxYAFBziJjJuCAiNqALlPnzFPdjtlaAVzEkpZADRmHESkAN2BaClcwOSoSEDk-APNgqRFgYVcARgSHXH8HORgGYGZ3GAoROwREk2BGSurzbDAI8jEoYFQAc2yHcygKAEd3YH66uAZ3Cjzek365RgB5VCosOwmphpNrAjl3Khg7AwBKNQA+cj3a456c6YcCEbEAOTkQFqqZkyaWsjaO7ruvX6QxGFDG60BJlyDSocmer3em3GWGarj+XRuQMGw1Gaygk0heEJck6iM+yNR5FQ7hAzB8hNm2NB4PxGxm0JmFDiwCo9XJ3zRRQxhI5vVoczKjAAggd7J8Ba0hQCkXNFstVuNWQy4MCcWC8QSkdtdvtDidVOdNDoACIFCjHAB0MAgAEkAMoLN1K44iwnuMCMO3S2UfeUon7o5XkrQFWSuABUmIcuuZBrZn2Ne1lxzOGm0cFtZUdzvdnu9R21QWz-sDkpl5tOSJMNaDMrgADJ23AAITAEQvJ4GQsUB1RKBBAwtuswI5HJvmAD8cCnYJl85MditBbtxddHq97S6PoaoqhgI61h45T5vTA7TiUA1oZmYAA1pVCMBqGMyG+-IISEgVIyjsABtMhajIABdIkkREd9EE-b80Vff8hHACBgJaUCYNPcw8NFUUEBgORmBoVwsAgdwoAAfRIsiKBo1AETIXAOCOTgOEkaR5EUZwsAdcUKB3BAHnHGAXjeVwACkIBkVB-1heEpPIN0QEwGR-xJFoACYAFZcCOB1OggY42CAA).

The error doesn't show up on the playground.

**Entity/Service Definitions**

```
{
    model: {
      entity: "customer",
      service: "palomma",
      version: "1",
    },
    attributes: {
      id: {
        type: "string",
        required: true,
        readOnly: true,
        default: () => ulid(),
      },
      firstName: {
        type: "string",
        required: true,
      },
      lastName: {
        type: "string",
        required: true,
      },
      age: {
        type: "number",
        required: true,
      },
      email: {
        type: "string",
      },
      createdAt: {
        type: "string",
        readOnly: true,
        required: true,
        default: () => new Date().toISOString(),
      },
      updatedAt: {
        type: "string",
        watch: "*",
        required: true,
        default: () => new Date().toISOString(),
        set: (updatedAt) =>
          updatedAt && !isNaN(Date.parse(updatedAt))
            ? updatedAt
            : new Date().toISOString(),
      },
    },
    indexes: {
      primary: {
        pk: { field: "pk", composite: ["id"] },
        sk: { field: "sk", composite: [] },
      },
    },
  }
```

**Expected behavior**
No Typescript warning should appear for omitting non-required fields.

**Errors**

```
Argument of type '{ firstName: string; lastName: string; age: number; }' is not assignable to parameter of type 'PutItem<string, string, string, { model: { entity: string; service: string; version: string; }; attributes: { id: { type: "string"; required: true; readOnly: true; default: () => string; }; firstName: { type: "string"; required: true; }; ... 4 more ...; updatedAt: { ...; }; }; indexes: { ...; }; }>'.
  Property 'email' is missing in type '{ firstName: string; lastName: string; age: number; }' but required in type 'Pick<CreatedItem<string, string, string, { model: { entity: string; service: string; version: string; }; attributes: { id: { type: "string"; required: true; readOnly: true; default: () => string; }; firstName: { type: "string"; required: true; }; ... 4 more ...; updatedAt: { ...; }; }; indexes: { ...; }; }, { ...; }...'.ts(2345)
test.ts(30, 7): 'email' is declared here.
```

**Comment by tywalch** [comment]
Hi @fmvfelipemonsalve 👋 

Are you able to share the version of `typescript` you are using? The playground uses the latest version of `typescript` (making it a great place to compare local behavior against the latest versions of `electrodb` and `typescript`) and it doesn't seem to show the same error. Depending on the version you're using, it may not be compatible with some of the inference syntax used in the library. The good news is, it might be as simple as updating your version 👍

**Comment by tywalch** [comment]
Closing this ticket but if you're able to share the info above feel free to reopen!

**Comment by nireak** [comment]
In case someboy arrives to this issue in the future: I had the same problem exposed here. Setting the parameter "strict": true in the "compilerOptions" in tsconfig.json solved my issue instantaneously. I hope this helps.
