### ISSUE TITLE
Support `ConsistentRead` option

### ISSUE THREAD

**Issue by harlowk** [tywalch/electrodb#370]
> [ConsistentRead](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_GetItem.html#API_GetItem_RequestSyntax)
Determines the read consistency model: If set to true, then the operation uses strongly consistent reads; otherwise, the operation uses eventually consistent reads.

Request to add `consistentRead` as an input option to `go`for GET requests. 

Expected: 
```
	const { data: payment } = await PaymentSource.get({id:'xxx'}).go({
            consistentRead: true
	}); 
	
	// operation uses strongly consistent reads
```

I'll open an MR for this if I can find time.

**Comment by tywalch** [comment]
Yo! So there isn't a `consistentRead` option but you can use 

```typescript
entity.get({...})
    .go({ 
        params: {
            ConsistentRead: true
        }
    });
```

The `params` option is a sort of "escape hatch" to put properties directly onto the ddb parameters sent off 💪

**Comment by tywalch** [comment]
Oh, I'm dumb, I see now this is a request to **add** this option, not that it "doesn't work". I can add it 👍

**Comment by harlowk** [comment]
> Oh, I'm dumb, I see now this is a request to **add** this option, not that it "doesn't work". I can add it 👍

Ha no, it was more the latter - forgot the params object took those untyped params!
