### ISSUE TITLE
Update nested Map value using set() method.

### ISSUE THREAD

**Issue by oise** [tywalch/electrodb#371]
**Describe the bug**
When I try to use `.set()` to update a nested map, the entire map gets replaced with the new value. This might be dueSee electroDb Playground link. 

**ElectroDB Version**
2.13.1

**ElectroDB Playground Link**
[Link](https://electrodb.fun/?#code/PQKgBAsg9gJgpgGzARwK5wE4Es4GcA0YuccYGeqCALgUQBYCG5YA7llXWAGbZwB2MXGBDAAUKKwBbAA5QMVMAG8wAUT5V2AT0IBlTADcsAY1IBfbhiiSwAIkRwjVSzABGNgNzijUPrgVUGFwRSAF5bTShUDAB9AKC4aL4GSTgPcVAwABUGXABrITUNKk1hMW9ffxz8sDC+OBZVdS0AClEwJTb2sElYRAAuDq6u-iLNAZsAvNwbfE6h-UxcLB9xgEYZua7iDEMTccnchmlpG03TWaGGKicsF1QqPAHFTfaH5KeXruLpOHG-bD4AHMNkMhuQ0FhyDABk50J9zp8Dh9QV9ND8-jcgSCUWQ4BCoTCMHCUQiUd5JCl1LhkTjvr9bJIjtiUdJLD95DhqYMce1UNsaTzXmj6TZ-lgsZ8hqTBS5YGNuYKwHSMQDgZKuqZ1ZqSRcNbr2uL4AAPR4KrqsqAAKwcNAFoOkuTtKK4OAQ0NsDuZOPJsiWDwGAG0JnBkjYALpa-WgvJO0EuxDu0W5L0o4DAMBGchXUg+qB+0i5OCaIRcORgaRMDQMJC4OQKQslNCYTnq9q5-OBiZVcNa+FR6XS5RxYJgTUASk8ojTYAABhWqEY6DOwFghAgsIXZ6hpDBs8u4EaTNIFOwwHy8LYrjc7g9ElAqNED6uaKcDrhOgA6eeL5rPIZvSRxm8cgvSRWwABYAFYAFoADZYIAJmxUwx0-YgqF-DMrEpW1FHPDA+gAcgASSSQjzBQz9ASgZoJyAA)

**Expected behavior**
I think the generated UpdateExpression should be 
`"UpdateExpression": "SET #comments.user = :comments_u0, ...`. 

I am currently only able to update a nested map without losing the previous data by using `.data()`

**Comment by tywalch** [comment]
Hi @oise!

The `set` method works on "root" attributes, so the behavior you describe is expected. To accomplish what you're doing however can be accomplished via the `data` method. [Here](https://electrodb.fun/?#code/PQKgBAsg9gJgpgGzARwK5wE4Es4GcA0YuccYGeqCALgUQBYCG5YA7llXWAGbZwB2MXGBDAAUKKwBbAA5QMVMAG8wAUT5V2AT0IBlTADcsAY1IBfbhiiSwAIkRwjVSzABGNgNzijUPrgVUGFwRSAF5bTShUDAB9AKC4aL4GSTgPcVAwABUGXABrITUNKk1hMW9ffxz8sDC+OBZVdS0AClEwJTb2sElYRAAuDq6u-iLNAZsAvNwbfE6h-UxcLB9xgEYZua7iDEMTccnchmlpG03TWaGGKicsF1QqPAHFTfaH5KeXruLpOHG-bD4AHMNkMhuQ0FhyDABk50J9zp8Dh9QV9ND8-jcgSCUWQ4BCoTCMHCUQiUd5JCl1LhkTjvr9bJIjtiUdJLD95DhqYMce1UNsaTzXmj6TZ-lgsZ8hqTBS5YGNuYKwHSMQDgZKuqZ1ZqSRcNbr2uL4AAPR4KrqsqAAKwcNAFoOkuTtKK4OAQ0NsDuZOPJsiWDwGAG0JnBkjYALpa-WgvJO0EuxDu0W5L0o4DAMBGchXUg+qB+0i5OCaIRcORgaRMDQMJC4OQKQslNCYTnq9q5-OBiZVcNa+FR6XS5RxYJgTUASk8ojTYAABhWqEY6DOwFghAgsIXZ6hpDBs8u4EaTNIFOwwHy8LYrjc7g9ElAqNED6uaKcDrhOgA6eeL5pDkOScZvHIGYlSqcYABYAFYAFoADZYIAJhsUcx0-XcAmaX8MysSkaFHQhlGIBRTDHGoAD4iDgKhmnJXDcA-c8MEIAByABJJJmLHVD2g-QEoGaCcgA) is an example of how you would accomplish that 👍

**Comment by oise** [comment]
Thanks for clarifying @tywalch.
