### ISSUE TITLE
Support for BigInt

### ISSUE THREAD

**Issue by codingnuclei** [tywalch/electrodb#386]
**Describe the bug**

I am building a geolocation service with Dynamodb which uses S2 to create geohashes.  These are very large numbers.  When trying to save an Entity with a large number it errors:
`Error thrown by DynamoDB client: \"Number 5226365420151572000 is greater than Number.MAX_SAFE_INTEGER. Use BigInt.`

However electrodb does not seem to support bigInt as a primitive. So i use the escape hatch type of `any` however now i get: 

`Invalid composite attribute definition: Composite attributes must be one of the following: string, number, boolean, enum`

As the error suggests if I use a bigint then i cant use it to create a composite key :(

Any suggestions?

**ElectroDB Version**
Specify the version of ElectroDB you are using
2.14.1

**Expected behavior**
Be able to use a BigInt to save a large number to the Db as a number

**Errors**

`Error thrown by DynamoDB client: \"Number 5226365420151572000 is greater than Number.MAX_SAFE_INTEGER. Use BigInt.`

`Invalid composite attribute definition: Composite attributes must be one of the following: string, number, boolean, enum`

**Additional context**

**Comment by zirkelc** [comment]
I'm not sure if the DynamoDB SDK for JavaScript supports BigInt, but as an easy workaround you could store the BigInt as String and use `get`  and `set` to convert between the types. Here's an example:

[Playground](PQKgBAsg9gJgpgGzARwK5wE4Es4GcA0YuccYGeqCALgUQBYCG5YA7llXWAGbZwB2MXGBDAAUKKwBbAA5QMVMAG8wAUT5V2AT0IBlTADcsAY1IBfbhiiSwAIkRwjVSzABGNgNzijUPrgVUGFwRSAF5bTShUDAB9AKC4aL4GSTgPcVAwABUGXABrITUNKk1hMW9ffxz8sDC)

**Comment by codingnuclei** [comment]
Hi thanks for the quick response :)

So I had a native solution (i.e one without electrodb) and it seemed to support BigInt.

`Error thrown by DynamoDB client: \"Number 5226365420151572000 is greater than Number.MAX_SAFE_INTEGER. Use BigInt.` 

This error which is thrown by the client suggests the SDK does support it.

I had the exact same idea as yourself regards the work around however not 100% confident in it as as part of a geospatial search you do a min max query (see img below).  Looks like when Dynamodb does this for strings it does not behave as a number would :(

<img width="790" alt="Screenshot 2024-05-21 at 09 13 52" src="https://github.com/tywalch/electrodb/assets/37954566/73a55cfe-0a72-42b9-8a5e-b52a0df72ddb">

Thanks

(fyi the playground link doesn't seem to work)

**Comment by zirkelc** [comment]
Oops, I updated the playground link: [Playground](https://electrodb.fun/?#code/PQKgBAsg9gJgpgGzARwK5wE4Es4GcA0YuccYGeqCALgUQBYCG5YA7llXWAGbZwB2MXGBDAAUKKwBbAA5QMVMAG8wAUT5V2AT0IBlTADcsAY1IBfbhiiSwAIkRwjVSzABGNgNzijUPrgVUGFwRSAF5bTShUDAB9AKC4aL4GSTgPcVAwABUGXABrITUNKk1hMW9ffxz8sDC+OBZVdS0AClEwJTb2sElYRAAuDq6u-iLNAZsAvNwbfE6h-UxcLB9xgEYZua7iDEMTccnchmlpG03TWaGGKicsF1QqPAHFTfaDp5eu4uk4cb9sPgA5hshkNyGgsOQYAMnOgPucPi4sACAJLqd4gz6ab6-G6A4EYsAAuBUAbNfQMBDoACUNQAfIMCe1gMAwOUFvIwFQoGBEQCsOoPqDiVE+GAAEJI1FUMkU6meRnwxnEElgGWUuA0kL056MpkstmYfzcv78gGCrrkKgisDk9UAfgAdFydLiAc0qfKCaY4Rcuoquvz4AAPR4MobSSwAKwcNHRBOkuTjjK4OAQUNsCfxjO8MigSweAwA2hMqjYALrm-0YvJJgkpxDpmx5LMEnOyfM-MCFisKn1nTr+5RxYJgb0e8QHXCdB3SK5GOjNZSbN62AAsAFYALQANm3ACYZmAB1Tp8rFzzJWiwABOAAMt4A7Ktr9e9+vVw-V7eX6tRaYT+0DoAlA7ruEAA)

Do you mean you get different results for between-query when the values in `sk` are stored as number vs. string?

**Comment by codingnuclei** [comment]
> Oops, I updated the playground link: [Playground](https://electrodb.fun/?#code/PQKgBAsg9gJgpgGzARwK5wE4Es4GcA0YuccYGeqCALgUQBYCG5YA7llXWAGbZwB2MXGBDAAUKKwBbAA5QMVMAG8wAUT5V2AT0IBlTADcsAY1IBfbhiiSwAIkRwjVSzABGNgNzijUPrgVUGFwRSAF5bTShUDAB9AKC4aL4GSTgPcVAwABUGXABrITUNKk1hMW9ffxz8sDC+OBZVdS0AClEwJTb2sElYRAAuDq6u-iLNAZsAvNwbfE6h-UxcLB9xgEYZua7iDEMTccnchmlpG03TWaGGKicsF1QqPAHFTfaDp5eu4uk4cb9sPgA5hshkNyGgsOQYAMnOgPucPi4sACAJLqd4gz6ab6-G6A4EYsAAuBUAbNfQMBDoACUNQAfIMCe1gMAwOUFvIwFQoGBEQCsOoPqDiVE+GAAEJI1FUMkU6meRnwxnEElgGWUuA0kL056MpkstmYfzcv78gGCrrkKgisDk9UAfgAdFydLiAc0qfKCaY4Rcuoquvz4AAPR4MobSSwAKwcNHRBOkuTjjK4OAQUNsCfxjO8MigSweAwA2hMqjYALrm-0YvJJgkpxDpmx5LMEnOyfM-MCFisKn1nTr+5RxYJgb0e8QHXCdB3SK5GOjNZSbN62AAsAFYALQANm3ACYZmAB1Tp8rFzzJWiwABOAAMt4A7Ktr9e9+vVw-V7eX6tRaYT+0DoAlA7ruEAA)
> 
> Do you mean you get different results for between-query when the values in `sk` are stored as number vs. string?

Yea exactly seems like there is different behaviour:

Working with number: 
<img width="1061" alt="Screenshot 2024-05-21 at 09 52 49" src="https://github.com/tywalch/electrodb/assets/37954566/5b783670-2da7-4ed3-bf67-77f673fe5bcf">


And then the same query as was with string example on the previous comments:

<img width="1067" alt="Screenshot 2024-05-21 at 09 51 13" src="https://github.com/tywalch/electrodb/assets/37954566/f678236b-2df3-49b8-801b-9ef8d1093f83">

As you can see it fails - as with string it gave a result

**Comment by zirkelc** [comment]
I think you have a typo in your string example. The first screenshot contains the values:
```
5226365420151572000
5226365420151572001
```

The second screenshot has a shorter max value. It misses a zero in the last three digits:

```tx
5226365420151572000
522636542015157201
```

It should be `2001` and not `201`.

**Comment by codingnuclei** [comment]
ah yes - sorry :(  

Ok looks like storing as a string will work (will build it out fully and run some tests).

I think in the long term it would be really neat if this lib could support large numbers...

I found some usual docs for how currently lib-dynamodb handle different primitives

https://github.com/aws/aws-sdk-js-v3/blob/main/lib/lib-dynamodb/README.md#marshalling-input-and-unmarshalling-response-data
https://github.com/aws/aws-sdk-js-v3/blob/main/lib/lib-dynamodb/README.md#large-numbers-and-numbervalue

Thanks for the support and fantastic project! 💯

**Comment by zirkelc** [comment]
To be honest, I would prefer to work with `string` than `bigint` if possible. If you have to do arithmetic, then of course you have to use them.

Bigint is not [JSON serialisable](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt#use_within_json), so you may have to convert them to string anyway. For example, returning a bigint from a Lambda function caused an error  (https://github.com/aws-amplify/amplify-category-api/issues/733) the last time I checked (might be possible now).

**Comment by codingnuclei** [comment]
Closing as no real use for electrodb to support bigints... yet 😄

**Comment by skyrpex** [comment]
I have a valid use case for bigint support.

First of all, DDB supports bigint since the payload for numbers is `{ N: "my-huge-number" }`, meaning that if you know you need to use bigints, you just cast whenever needed (e.g. `{ N: myBigInt.toString() }` and `const myBigInt = BigInt(Item.myBigInt.N)`.

Now, my use case is using DDB to handle transactions that increase a revision number, which is a bigint. See the following entity:

```ts
const Transaction = new Entity({
	model: {
		entity: "transaction",
		version: "1",
		service: "transactions",
	},
	attributes: {
		streamId: {
			type: "string",
			required: true,
		},
		revision: {
			type: "number",
			required: true,
		},
	},
	indexes: {
		transaction: {
			pk: {
				field: "pk",
				composite: ["streamId"],
			},
		},
	},
});
```

Committing a transaction is done like this:

```ts
Transaction.update({
	streamId: input.streamId,
})
	.add({
		revision: input.events.length,
	})
	.where(({ revision }, { eq }) => {
		// Here type checks fail, and runtime too.
		return eq(revision, input.expectedRevision);
	})

```

Problems:

- electrodb won't allow me to pass a bigint
- even if I ignore the type checks, it fails at runtime
- can't use type string for revision along with the `add()` operation (also not sure it would work)
- revision needs to be bigint since it will grow beyond the max integer

**Comment by tywalch** [comment]
Hi @codingnuclei @skyrpex 👋 

I replied in the ticket opened by @skyrpex, but I thought I'd crosspost my take here as well for visibility: https://github.com/tywalch/electrodb/issues/467#issuecomment-2614024275
