### ISSUE TITLE
More Hassle Than Help: Prefix Issues in Composite Keys and Other Frustrations Lead Us to Drop ElectroDB :( 

### ISSUE THREAD

**Issue by rdzidziguri** [tywalch/electrodb#423]
**Describe the bug**
prefixes not trimmed from keys.
Composite keys needed to be handled appropriately (again, they were not trimmed).

**ElectroDB Version**
2.14.2

**ElectroDB Playground Link**
[Playground Link](https://electrodb.fun/?#code/JYWwDg9gTgLgBAbzjAnmApnAogOxsVAJXQGNoATAGmzwJTgF84AzKCEOAcnQBtSY25AEacA3AChx6AB6RYcMjgDO8AG7AlBAJI5mEOAF44OdAHca+VAAoE4uPbggI5XgC5Edh1-S1U7gEQAahrauhD+lJ5e9qroUJoQOAEAjBFR0Upx6iToAQAKAMoF-ukMkV4AhjACwEIArjDoSu620Q7A5C3pbfaoGAEqUMA4AOZpPdHMwLydcP55ANLjEw5Q6ACOdcBrswJ16N0OZYf2ZOAQmo0AsugwFV0rDn25c4PDY+WPLNM8s-4FS0+jzWm226F2UH2QJWpiqJAAFu4ANqcEC3CrkKoVTgAXWhE0yMHcVgA+tQEGi7pi7gwAJSGAB8cAABgASCno6kVAB0JDWVXBAHkcAwAMTsykYrHcupganoYgVJSJMUSznSlxKPnAMD4FXMk6MfEOSVch5fZ4BEAVMDLR5gNgYWDTZoeL7RPnoAXkYUtZBoF7+HB1EBCOIROAgrY7dx7TDHd1eWXyn1JRD+-pzYOh8PUKNgiH7I2GibJgWK5VppCW141UYR-Mx5CQ+PGx6a7W64CJP01-xvet5jbR8GxluMEtHNvRRuj5v7Q0MUrQ4YuaRNc1tB2gCpQFCblZgADWB-dUxm+UBk7ajXAPAFAUCWgK4oQHQYdsTZ0glxeKI6uLThMJBKu87icDgiToJw17Fu6Sgnm6ib2OevwBACn7ut+FwEH+nDYb+Nx3IBsFeLeYD3o06EACoAMKvgRuFERUH5AT0IGaKM4GQSYMHukuEwCUc4h0pIMhyPAzxwHkjpxKgBR3CgBQIug1qGBYdDEGQUDkAAPM8EDMHA6iXDoegMqIQA)

**Additional context**
Unfortunately, enough is enough, and today, on our global hands-all call, we decided to drop the library altogether. We had issues with it earlier as well. Still, lately, those problems and constant search for workarounds got to the boiling point where the team decided that for any advanced single table architecture with a bunch of composite keys, the library fights us back every time we tried to use it. It is highly opinionated and does not even align with some of DDB's philosophy. 

While some of the ideas behind it seem very attractive when it comes to accurate data, you have to fight back constantly, and our engineers did not find any value after they were tasked to remove prefixes from keys because of how schema is designed. 
This library is perfect for small to maybe even mid-size projects, but when it comes to many attributes and a tenth of entities. The enforcement that it puts is where each attribute is mapped to a column even if you do not need those, and you lose tons of capabilities as soon as you map an attribute to filed SK, for example, or, let's say, you have an attribute. Still, you do not want it to be stored separately, and it is only to build a composite key, which made it a dealbreaker for us. 

Good luck to the library maintainers, and if things change in the future, we should consider revisiting our decision. Still, for now, we are leaving this thread here for others to be aware of all the little issues they might face if their schema is more complex than it is usually described in beginner-level dynamodb books.

**Comment by tywalch** [comment]
Hi @rdzidziguri :wave: I'm sorry to hear you experienced friction using the library. Thank you for the feedback and good luck with your project!
