### ISSUE TITLE
Ability to prefix/postfix attribute templates

### ISSUE THREAD

**Issue by nonken** [tywalch/electrodb#437]
**Describe the bug**
This is not a bug I would say but a request 🙏🏻. We are using a shared dynamo instance for running a bunch of tests. Before using electrodb we prefixed the pk with a random test namespace so that any kind of test data would be guaranteed to not overlap with other data.

With ElectroDB we now need to have a similar namespace prefix (or) postfix and I see we can use the attribute template. The issue with that is that when we use our own template it overrides the ElectroDB defaults and it doesn't seem to be possible to use the same native template structure.

The solution that we though of but obviously might be totally off is:

```
pk: {
    field: 'pk',
    composite: ['org'],
    template: (originalTemplate) => {
        return `${prefix}${originalTemplate}`
    }
}
```

It can be that I am thinking about this wrongly and that the idea to preserve the native template isn't really needed. The prefix/postfix also shouldn't break any lib behaviour.

Looking forward to hear what you think 🙏🏻

**ElectroDB Version**
2.15.0

**ElectroDB Playground Link**
(if possible) Use the [ElectroDB Playground](https://electrodb.fun) to recreate your issue and supply the link here to help with troubleshooting.

**Entity/Service Definitions**
Include your entity model (or a model that sufficiently recreates your issue) to help troubleshoot.

```
{
    model: {
        entity: "my_entity",
        service: "my_service",
        version: "my_version"
    },
    attributes: {
        org: {
            type: "string"
        },
    },
    indexes: {
        record: {
            pk: {
                field: 'pk',
                composite: ['org'],
                template: (originalTemplate) => {
                    return `${prefix}${originalTemplate}`
                }
            },
            sk: {
                field: "sk",
                composite: ["prop2"],
            },
        }
    }
}
```

**Expected behavior**
A way to maintain the native attribute template while pre or postfixing attributes.

**Comment by tywalch** [comment]
Hi 👋 

Can you post an example of your key structure? I can put together some options.

**Comment by nonken** [comment]
Ohai 😄 I hope this is what you are asking for:

```
indexes: {
    runs: {
      pk: { field: 'pk', composite: ['org'] },
      sk: { field: 'sk', composite: ['portfolioId', 'jobId', 'id'] }
    },
    jobs: {
      index: 'gsi1pk-gsi1sk-index',
      pk: { field: 'gsi1pk', composite: ['org'] },
      sk: { field: 'gsi1sk', composite: ['portfolioId', 'jobId', 'runAt'] } 
    },
    runStatus: {
      index: 'gsi2pk-gsi2sk-index',
      pk: { field: 'gsi2pk', composite: ['runStatus'] },
      sk: { field: 'gsi2sk', composite: ['runAt', 'org', 'portfolioId', 'jobId'] }
    },
  }
```

The primitive idea was to just prefix/postfix the pks with a random string, while maintaining the ElectroDB template structure. Is this what you were asking for? 🙏🏻

**Comment by nonken** [comment]
@tywalch 🙏🏻 scope works exactly in the way we need it to work atm 🙏🏻 thank you for sharing this, really appreciate it. If anyone else stumbles into a similar issue hopefully this will be a useful reference.
