### ISSUE TITLE
`map` attributes should allow arbitrary properties

### ISSUE THREAD

**Issue by solaris007** [tywalch/electrodb#450]
**Describe the bug**
When wanting to specify an attribute of type `map`, a full map-schema via the `properties` setting is required, effectively locking down what kind of maps can be stored for that attribute. There are use-cases however, where an attribute is desired to be a map, yet the contents of that map may vary. Similar to OpenAPI specs, we could envision to allow setting `additionalProperties: true`, in which case the value would be validated as a valid object but not enforce a schema within the object.

Currently this needs to be worked around like this with custom validation:
```js
    data: {
      type: 'any',
      required: false,
      validate: (value) => !value || isNonEmptyObject(value),
    },
```

**ElectroDB Version**
3.0.1

**Comment by tywalch** [comment]
Hi @solaris007 :wave: 

This sounds like a good job for [the `CustomAttributeType` function](https://electrodb.dev/en/reference/typescript/#customattributetype). It allows you to have fine-grain typing for an attribute; here is a [playground example](https://electrodb.fun/?#code/PQKgBAsg9gJgpgGzARwK5wE4Es4GcA0YuccYGeqCALgUQBYCG5YA7llXWAGbZwB2MXGBDAAUKKwBbAA5QMVMAG8wAUT5V2AT0IBlTADcsAYziEAwqlxUokgIJUq2AEaoqcACqbppAL7cMNmAARIhwRo6wTkEA3OJGUHxWYFQMTgikALzBmlCoGAD6KWlw+XwMknAx4lRepO50WHwA5gAiDClgWYqiYMm1AFxgAOQ13gCMQ-g9YPGo6oN8qJJOmLF+AD5K06NwgyO1AExDsb1cWBhWg1bYzSdgCAyXRI6NTWtgm929O3s7AMzHaZlCpXF63abwXBGbDSDQJUE3N6iHxxBJJeqvTpgPhwFiqdRaAAU0y+vTAklgiEGpLJYH4GhqgyCKVwAGtcEEprTevpMLgsPDgmNOdNacQMIYTEyWayGNJpEFRWAfFyye0Xi43LhqUrelgYDruWSfsFrq8RUbeuQ0Oc4Abkhh0LrlaraTB2gxDZaTRYrDZ7BrXB5agAeDHNNopAB8hKGDD4miGAEpXWSVUr07TGvAAB54L208jxDD2mnc6SsguWs6Ie1BCsWy29eIyKD8tyDADaQX1QQAus7epnLWyq0aawg62zG02W7J27swJ2B02UUa12npsPlEV0srREnYqJ4okFPqsUMxgcAUfw00AHTQuDtOCE0n6wgQj1V2bzMAAVlTE19nGIYt2RJN7yaKBCUPcQ70fcgXzfaYPzAL8UirYCdiOVMzguKg9gAKygOg+EmJUHieIZcEkdg6AoocIKgmC4NEBCn2Q98YE-Xp3UwrZaWw2oAVTYFFxGBpmkwRiyUhaEsFhAU+D2GAoDwZ5UC4LhZJRHxIOg2DoiAA).

A lot of people pair this with a validation library like `zod` or `jsonschema` to accomplish the validation side of things :+1:

**Comment by solaris007** [comment]
Hi @tywalch :) Thank you for your answer!

Certainly, the `CustomAttributeType` would be a great choice for more complex validations / types, but seems counter-intuitive / over-engineered for the simple case where we want to accept just any map?

**Comment by tywalch** [comment]
I suppose this was mainly to demonstrate that any type could be used, even something simple like `Record<string, string>` or `{ [key: string]: unknown }`, which sounds like what you're trying to accomplish. Does this fall short of what you might be expecting?

**Comment by tywalch** [comment]
Closing this ticket, though feel free to reopen it if you'd like any follow-up conversation on this topic :+1:
