### ISSUE TITLE
Are there any plans to support transactions

### ISSUE THREAD

**Issue by kujtimiihoxha** [tywalch/electrodb#61]
Thanks for the library and the work you have done here 👍 

I wanted to see if I can use this library for my use case but there are cases where I need to use [transactions](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/transaction-apis.html). Is there any way I can do that with the library?

**Comment by kujtimiihoxha** [comment]
Oh I think I could just use `.params()` and  build the transaction items manually 🤦

**Comment by tywalch** [comment]
There are tentative plans to make it a more formal method. There are a few things slotted before that, namely complex structure support, a new update/patch api, and a lot of clean up/refinements.
