### ISSUE TITLE
Allow return values on patch/update request

### ISSUE THREAD

**Issue by garretcharp** [tywalch/electrodb#71]
Currently, whenever doing a patch or an update the response is null even when I set the params to have ReturnValues set to "ALL_NEW". I would like for the library to handle return values and parse the items for me.

**Comment by tywalch** [comment]
This is something I've been wanting to add support for, I'll prioritize this 👍

**Comment by garretcharp** [comment]
Another thing you might think about adding with this too is support for a parse method where you give it an item from Dynamo and it returns the parsed object using all the getters setup.

**Comment by tywalch** [comment]
Small update on this: Unless I find a critical issue, this will be in a PR tomorrow along with complex object support (map, list, set) 👍

**Comment by tywalch** [comment]
Syntax will use Query Option,`response`, with values: `"default" | "none" | "all_old" | "updated_old" | "all_new" | "updated_new"`

Use like this:
```
.go({response: "all_new"});
// or
.params({response: "all_new"});
```

**Comment by garretcharp** [comment]
That great to hear thanks for the update
