### ISSUE TITLE
Ability to parse items (DynamoDB Streams)

### ISSUE THREAD

**Issue by garretcharp** [tywalch/electrodb#74]
Looking to start using dynamodb streams would be nice to be able to parse the items it sends me using electrodb. Could be something on the entity level and service level. For example maybe I only really care about one item type for a specific operation that occurred so I do `entity.parse(dynamoItem)` and it could return the parsed item if it is of that entity type or null/error if not. Then on the service level, it could return type: 'entityName' item: parsedItem

**Comment by tywalch** [comment]
This was an easy add because there was already a method that did this cleanly. I just added a PR that adds types to a new method, `parse()`.

**Comment by tywalch** [comment]
This was not done correctly, I should not have rushed this. Apologizes Garret

**Comment by garretcharp** [comment]
No worries

**Comment by tywalch** [comment]
I merged this PR, I will let you close the issue when you've had time to work with it. Note that the `parse` method expects a full dynamodb response, though you can of course "fool" it by passing an object with an `Item`, `Items`, or `Attributes` property.

https://github.com/tywalch/electrodb/pull/76

**Comment by garretcharp** [comment]
From my small little test, it seems to be working as expected so going to close this now.

**Comment by pjvds** [comment]
Is there actually a nice way to switch entity types for change events from multiple entities?
