### ISSUE TITLE
Ability to make composite attribute from map item

### ISSUE THREAD

**Issue by garretcharp** [tywalch/electrodb#77]
I would like to be able to make an index that takes fields from a map item. For example say I have an item that belongs to a user, maybe a comment or something like that. I store the item in the comment entity as a partial of the user entity so I store it as a map, but trying to make an index of `user.id` does not work currently.

**Comment by tywalch** [comment]
I did a lot of thinking about how complex objects might play a role in indexes. In the end, I think allowing for nested attributes to be used in composite keys opens the door to a lot of complexity and ultimately might hurt DX after implementing checks and validations on all the edge cases. For now, I'd like to keep composite attributes simple, even if that means a bit of denormalization on the item.

**Comment by tywalch** [comment]
@garretcharp Im going to close this ticket for now but please let me know if you have any further issues or suggestions 👍
