### ISSUE TITLE
Upserts?

### ISSUE THREAD

**Issue by joyrexus** [tywalch/electrodb#85]
Greetings BDFL of Electrodb!

Curious if Electrodb supports "upserts" out-of-the-box (create if not exists, otherwise patch/update).

We're looking to create an item if it doesn't exist with all of the same attributes (including those used in the PK and SK) that would be created with a `put` or `create` ... otherwise to just update the item (viz., all attributes except for those used in the PK or SK).

This can be done with a `try { create } catch { patch }`, but was thinking there might be something analogous to dynamodb's [**UpdateItem**](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_UpdateItem.html) command.

[Here's a gist](https://gist.github.com/joyrexus/7f73ccd72693ed99b5a76fe0315bb2ce#file-upsert-js-L51-L94) showing what we've tried thus far.

**Comment by tywalch** [comment]
Howdy!

ElectroDB uses DynamoDB's `UpdateItem` under the hood when calling `.go()` on both the `update()` and `patch()` methods. 

I put together a response in the electrodb playground here: https://tinyurl.com/electrodb-ticket85

In a nutshell, I'm working on a patch to include the PK and SK composite attributes in updates. This should address what you're seeing. Feel free to modify the playground and send a link back (the url includes the code body) if you have other questions. Note that the playground uses the latest version of ElectroDB, so there are some small differences from your version `0.9.52`. The patch I am making however will include a deployment for <1.0 compatible versions too though 👍

**Comment by joyrexus** [comment]
Appreciate your efforts on this!

Hmm. I tried testing with the earlier patched version as well as the most current version and found that update operations were only updating _existing_ items, but didn't persist new items when the given key wasn't found.

I was using the [same code as before](https://gist.github.com/joyrexus/7f73ccd72693ed99b5a76fe0315bb2ce#file-upsert-js-L51-L94) to test, but with the patched versions (`0.11.1` and `1.4.5`).

**Comment by tywalch** [comment]
I see the issue. My update didn't add the Entity Identifiers (`__edb_e__` and `__edb_v__`) to the update, so while it made the record, the `get` (and `query`) methods weed the record out. You can see this if you adding the [query option](https://github.com/tywalch/electrodb#query-options) `ignoreOwnership` to equal `true` (note: I don't believe that option is in `0.11.1`)

**Comment by joyrexus** [comment]
Tested it out and looks like upsert functionality with `update` is now working as expected. Thanks again!
