### ISSUE TITLE
Add support for AWS SDK v3 (`@aws-sdk/client-dynamodb`)

### ISSUE THREAD

**Issue by moltar** [tywalch/electrodb#99]
Would be great to have support for AWS SDK v3.

```ts
import { DynamoDBClient } from '@aws-sdk/client-dynamodb'

const client = new DynamoDBClient({})
```

Thanks!

**Comment by tywalch** [comment]
I'll begin taking a look at this, thank you. As a stop gap, the .params() might be useful in the short term.

**Comment by tywalch** [comment]
Something like this should also work in there interim: 

```typescript
import { DynamoDBClient } from '@aws-sdk/client-dynamodb';
import { 
  DynamoDBDocumentClient, 
  PutCommand,
  GetCommand,
  ScanCommand,
  QueryCommand,
  UpdateCommand,
  DeleteCommand,
  BatchGetCommand,
  BatchWriteCommand,
} from '@aws-sdk/lib-dynamodb'

const clientV3 = DynamoDBDocumentClient.from(new DynamoDBClient({}));

class DocumentClientWrapper {
  client: DynamoDBDocumentClient;
  constructor(client: DynamoDBDocumentClient) {
    this.client = client;
  }
  get(params: any) {
    return {
      promise: async () => {
        const command = new GetCommand(params);
        return this.client.send(command);
      }
    }
  }
  put(params: any) {
    return {
      promise: async () => {
        const command = new PutCommand(params);
        return this.client.send(command);
      }
    }
  }
  update(params: any) {
    return {
      promise: async () => {
        const command = new UpdateCommand(params);
        return this.client.send(command);
      }
    }
  }
  delete(params: any) {
    return {
      promise: async () => {
        const command = new DeleteCommand(params);
        return this.client.send(command);
      }
    }
  }
  batchWrite(params: any) {
    return {
      promise: async () => {
        const command = new BatchWriteCommand(params);
        return this.client.send(command);
      }
    }
  }
  batchGet(params: any) {
    return {
      promise: async () => {
        const command = new BatchGetCommand(params);
        return this.client.send(command);
      }
    }
  }
  scan(params: any) {
    return {
      promise: async () => {
        const command = new ScanCommand(params);
        return this.client.send(command);
      }
    }
  }
  query(params: any) {
    return {
      promise: async () => {
        const command = new QueryCommand(params);
        return this.client.send(command);
      }
    }
  }
}

// client compatible with ElectroDB:
const client = new DocumentClientWrapper(clientV3);
```

**Comment by moltar** [comment]
Thanks Tyler, I'll give it a shot!

**Comment by ShivamJoker** [comment]
Any updates on this?

**Comment by tywalch** [comment]
I have been traveling frequently for the past few weeks and haven't had a chance to get this in. This is still on my radar and I am hoping to have more news on it soon.

**Comment by tywalch** [comment]
@ShivamJoker @moltar I have just [merged and published](https://github.com/tywalch/electrodb/pull/109) v3 support in version `1.7.0`! Please let me know if you have any issues when using the v3 client and I will make it priority to resolve your issues 👍

**Comment by ShivamJoker** [comment]
Thanks a lot I'll try it.
Also I am using CDK so should I just make a table and your library will add GSI based on schemas?

**Comment by moltar** [comment]
Nice one @tywalch!

I still haven't had a chance to try this package out 🙈 

Maybe this will give me a boost!

**Comment by moltar** [comment]
Btw, should `@aws-sdk/lib-dynamodb` be a peer dep?

Because this will increase bundle sizes for everyone, even if they do not use the v3 SDKs.

These v3 SDKs are quite bloated, unfortunately!

https://bundlephobia.com/package/electrodb@1.7.1

![screenshot-20220321T105644-Fqy4cKb2](https://user-images.githubusercontent.com/491247/159203422-b8bf32bf-7451-473c-bdaa-fbaf85b58cda.png)

**Comment by ShivamJoker** [comment]
@moltar so are there any benefits of using V3 with electrodb? In terms of performance

**Comment by moltar** [comment]
Pros:

 - Future-proofing. The end of support for v2 will probably be announced soon, since v3 has been out for a while. And other languages had already EOS announced.
 - Native TypeScript support, without `@types/*`
 - It is mostly codegen'ed from standard definitions, which ensures that all APIs are compatible
 - Modular (use only what you need)
- v2 is a [heavy dep](https://bundlephobia.com/package/aws-sdk@2.1096.0) _(if you bundle)_ (3MB). In v3, take a few common clients, and it'll be ~ 1-2MB and there is a TON of room for them to improve this still. The code is not yet well optimized for bundling.

Cons:

- Not available in the Lambda environment. _(Although this was an anti-pattern anyways, and was not recommended to be used that way.)_
- Less stable and less battle-tested.

**Comment by ShivamJoker** [comment]
Got it. Thank you
